### ISSUE TITLE
Possible issue with n- and m-dashes

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#102]
The TOC Items are created but the in page link to the heading is not inserted. Suspected cause is the heading matching is not finding a match possibly do to WP transforms of post content.

refs:

 - https://wordpress.org/support/topic/h2-jumplink-no-longer-working/

**Comment by Sanjeevsetu** [comment]
This issue is similar to https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/306 and we have fixed the issue there so going to close it.
