### ISSUE TITLE
Modula and Shortcodes Ultimate

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#109]
Reported possible plugin conflict.

`Uncaught TypeError: attributes[attributeName].split is not a function
in js.cookie.min.js`

ref: https://wordpress.org/support/topic/some-sliders-broken/

**Comment by shazahm1** [comment]
Potential resolution found by another user.

ref: https://wordpress.org/support/topic/plugin-conflict-ultimate-shortcodes/#post-12830623

**Comment by Zabi09** [comment]
I have added Ultimate Shortcodes and Wpdiscuz along with Easy TOC but still, I am not able to get the error, and its working fine at the moment - https://prnt.sc/gxzoSQEmTa_J BUT if someone has the issue then please let us know and we are going to fix it
