### ISSUE TITLE
Table of Contents dont show up

### ISSUE THREAD

**Issue by flyzy2005** [ahmedkaludi/Easy-Table-of-Contents#116]
Hi,

It may be caused by conflicts between my theme and Easy Table of Content. I am writing to see if you can give me some suggestions on how to fix this issue. Thanks in advance.

If my first H2 includes a <a> link, Easy Table of Content won't work.

![image](https://user-images.githubusercontent.com/16304483/92316969-d078e580-f02d-11ea-9a60-fac2facaec44.png)

If no <a> link is included, it works quite well.

![image](https://user-images.githubusercontent.com/16304483/92316977-f1413b00-f02d-11ea-809e-f4ae2900a372.png)

Here is how my theme retrieves the article content:

![image](https://user-images.githubusercontent.com/16304483/92317090-33b74780-f02f-11ea-847a-25f10b4f4c40.png)

For detailed informtaion, here are the two links:

- https://tiaozhuan.win/2018/08/10/hello-world/ 
- https://tiaozhuan.win/2020/09/06/hello-2/

Thanks for your attention.

**Comment by flyzy2005** [comment]
If I change Position from 'Before First Heading' to 'Top', it works even if the first H2 includes a <a> link.

![image](https://user-images.githubusercontent.com/16304483/92317185-cb696580-f030-11ea-9068-c06884105bf0.png)

**Comment by flyzy2005** [comment]
Further information.

The table of contents located at widgets works well, but the default display style is none.

![image](https://user-images.githubusercontent.com/16304483/92491336-b35a3780-f224-11ea-9e35-24efe01e3c98.png)

I would really appreciate if you could fix this issue.

Many thanks

**Comment by flyzy2005** [comment]
If the H2 included a a tag, the ez-toc-section could not be generated properly.

![image](https://user-images.githubusercontent.com/16304483/95284284-72d7f300-0890-11eb-864c-025d59ad7ff1.png)

**Comment by flyzy2005** [comment]
> **RE: The table of contents located at widgets works well, but the default display style is none.**
> 
> Please do the following:
> 
> * Navigate to the Table of Contents Settings admin page.
> * Disable the "Toggle View" option.
> * Disable the "Initial View" option.
> * Save the changes.
> * Clear your cookies.

Thanks. This fixes the 'style is none' issue. But how about the first one? If H2 contains a a tag, TOC cannot work properly.

**Comment by shazahm1** [comment]
Sorry, but I am not able to replicate it when using the [Kadence theme](https://kadence-theme.com/).

**Comment by Zabi09** [comment]
@flyzy2005 I have tested with Kadence theme and the TOC is working fine - https://prnt.sc/MvVOeJOKzLkQ

Github is for tried and tested bugs.
Please create a ticket for this on https://tocwp.com/contact/
once it's verified by our technical team, then we will re-open or create a bug report.
