### ISSUE TITLE
Link doesn't work with emoji in title

### ISSUE THREAD

**Issue by Zarosch** [ahmedkaludi/Easy-Table-of-Contents#117]
Hey,

when I'm put an "☑️" in a title, the anchor will doesn't work.

Best regards,
Zarosch

**Comment by Zabi09** [comment]
I have tested a lot and found that the emojis are working perfectly with our plugin - https://prnt.sc/V-sI32y0yjm_

Github tickets are for valid and re-creatable bugs and for support please get in touch with us via the website and tell us more details about how exactly how you are adding it and our team will look into it
