### ISSUE TITLE
Possibility of adding "a Hook Before/After the TOC container"

### ISSUE THREAD

**Issue by andreiger** [ahmedkaludi/Easy-Table-of-Contents#119]
Hi Steven,

Thanks for you awesome work with the TOC - absolutely love it!

I did however encounter the following situation:

1. Using a theme, I enabled a right-sidebar and placed the TOC within that sidebar as a widget
2. Everything looks splendid on desktop, but on mobile my TOC is all the way at the end of the content, and not above the first H2 heading as I'd want it
3. Spoke to the theme's developers and they can only help me with that if the TOC itself has a "Hook Before/After the TOC container" - their exact words: "be nice if they added a Hook Before/After the TOC container" 

I don't know how to explain this any better, but I do hope you can help out with this and possibly add this hook with a next release.

This is a blog post with the example I'm mentioning: https://krave.ro/103-2/
Looks good on desktop, but on mobile, the TOC is at the end of the content, and there's seems to be no way of dragging it above the first H2, without this hook :)

Please let me know if it's possible to implement this hook!

Cheers and thx again for your great work!

**Comment by shazahm1** [comment]
There are the `ez_toc_before_widget` and `ez_toc_after_widget` actions available.  Or is something else needed? If I can get more specifics that would help. Thanks!

**Comment by andreiger** [comment]
Hi Steven,

Just mentioned your lines to the theme developers. Will wait for their reply too see if those actions can do the trick, but will let you know. Thanks too!

**Comment by diggeddy** [comment]
Hi @shazahm1 

Those hooks only exist when the ToC is displayed as a widget not when the ToC is automatically output to the post content.

What Steven was trying to achieve was to have the ToC automatically added to the post content. 
On larger screens we look to position the ToC outside the post content as a sticky element.
Trying to avoid JS - the CSS solution would require an additional wrapper.

Options for Hooks would be either around the ez-toc-container

```
<!-- hook before container -->
<div id="ez-toc-container" class="ez-toc-v2_0_11 counter-hierarchy counter-decimal ez-toc-grey">
    <div class="ez-toc-title-container"></div>
    <nav></nav>
</div>
<!-- hook after container -->
```
or inside that container:

```
<div id="ez-toc-container" class="ez-toc-v2_0_11 counter-hierarchy counter-decimal ez-toc-grey">
    <!-- hook before inside container -->
    <div class="ez-toc-title-container"></div>
    <nav></nav>
    <!-- hook after inside container -->
</div>
```

Hope that helps !

**Comment by shazahm1** [comment]
ahhh, ok, I was looking at the widget action because of point `1` in the OP. There are additional hooks; `ez_toc_before` and `ez_toc_after`. These hooks run inside the container as shown in your second example above. So, if I understand correctly, you have the action hook you need.

**Comment by andreiger** [comment]
Thanks for letting us know Steven!

Will check with David if it's possible to move the TOC at a desired position in my singlePost content using the hook you mentioned.

Keep you posted!

**Comment by diggeddy** [comment]
Unless i am missing something the `ez_toc_before` comes after `<div class="ez-toc-title-container"></div>`

@andreiger we could probably work with this but it means the Title and Toggle won't be sticky only the ToC List. Your call.

**Comment by shazahm1** [comment]
Yes, sorry it does looks like it fires after the title. That not actually the intent though. So it appears a change will have to be made. I'll likely deprecate these actions and add new action in the locations that they should be fired.

**Comment by Zabi09** [comment]
Pushed in 2.0.30
