### ISSUE TITLE
Very slow performance with large number of entries

### ISSUE THREAD

**Issue by jgadbois** [ahmedkaludi/Easy-Table-of-Contents#125]
I have some posts with 60+ `<h3>` tags and the plugin can take 5 seconds + to generate the plugin.

If I disable the multi-byte string search/replace it speeds up enormously.  Could we have an option to completely disable multi-byte support to speed up performance (or maybe there are problems with doing this?).

**Comment by shazahm1** [comment]
If you submit a pull request for a change, I'll definitely consider it. Not sure if it is possible, but instead of a setting, perhaps detect if MB is required or not.

**Comment by jgadbois** [comment]
Thank you, I will take a look - when would MB be required?  Is it based on the current language?

**Comment by shazahm1** [comment]
MB would be required depending on the language, even English if emoji is used.

**Comment by Sanjeevsetu** [comment]
Due to inactivity and lack of more information I am closing it
