### ISSUE TITLE
Feature request: Add toggle state class to container

### ISSUE THREAD

**Issue by tyrann0us** [ahmedkaludi/Easy-Table-of-Contents#129]
Currently, there is no way to check whether the ToC list is open or closed; clicking the icon toggles the state, but the change is not reflected in e.g. a container class. This makes it impossible to conditionally apply styles based on state, such as turning a down-pointing arrow up in the toggle icon when the list is open.

It would be great if you could add an HTML class to the container that reflects the toggle state, e.g. `is-inactive`/`is-active`, `ez-toc-container-closed`/`ez-toc-container-open` or similar.

Thanks!

**Comment by tyrann0us** [comment]
For now, I'm doing a quick & dirty workaround that uses `MutationObserver` to listen for changes of the list's `style` attribute and toggles a class on the container.

In `easy-table-of-contents.js`:
```javascript
export class TocHelper {
  constructor() {
    this.target = document.querySelector(TOC_LIST_SELECTOR);
    this.container = document.querySelector(TOC_CONTAINER_SELECTOR);
  }

  initialize() {
    if (! this.target) {
      return;
    }

    this.addMutationObserver();
  }

  addMutationObserver() {
    const observer = new MutationObserver(this.observerCallback.bind(this));

    observer.observe(this.target, {
      attributeFilter: ['style'],
      attributeOldValue: true,
    });
  }

  observerCallback(mutationsList) {
    mutationsList.forEach(mutation => {
      if (mutation.oldValue === 'opacity: 1;') {
        // the list has been opened, and the animation is done.
        this.container.classList.add(TOC_CLASS_OPEN);
      } else if (mutation.oldValue === 'opacity: 0; display: none;') {
        // the list has been closed, and the animation is done.
        this.container.classList.remove(TOC_CLASS_OPEN);
      }
    });
  }
}

const TOC_LIST_SELECTOR = '.ez-toc-list';
const TOC_CONTAINER_SELECTOR = '#ez-toc-container';
const TOC_CLASS_OPEN = 'open';
```

To initialize it:
```javascript
import {
  TocHelper
} from './easy-table-of-contents';

const tocHelper = new TocHelper();

tocHelper.initialize();
```

Not clean at all, but works.

**Comment by Zabi09** [comment]
Pushed in 2.0.29
