### ISSUE TITLE
Focus to Active H* during scrolling (with fixed side or top bar)

### ISSUE THREAD

**Issue by mikulabc** [ahmedkaludi/Easy-Table-of-Contents#133]
I have seen this https://codepen.io/bramus/pen/ExaEqMJ
this here https://www.foxy-solutions.com/salesforce/css-variables-in-lightning-components/
this https://www.indowhiz.com/articles/en/general-guidelines-to-improve-your-website-speed/#Mobile_phone_domination
this https://www.safewise.com/resources/apartment-security/
and this https://lab.hakim.se/progress-nav/

since i am not a developer i do not know how to make this so it shows during scrolling the active header

any way we can get this with Easy TOC?

thx! mik

**Comment by Zabi09** [comment]
Pushed in TOC PRO -  1.0.1
