### ISSUE TITLE
Doesn't work in WooCommerce category description

### ISSUE THREAD

**Issue by e-orlov** [ahmedkaludi/Easy-Table-of-Contents#134]
I have HTML code in the description field of my WooCommerce category pages. HTML code is added on different ways: with this plugin https://wordpress.org/plugins/visual-term-description-editor/ or with this one: https://codecanyon.net/item/woocommerce-category-article-pro/15497186

Both plugins work like a charm and interpret shortcodes from other plugins. But not of EasyTableOfContents :( - 

- without shortcode Table of Content just doesn't appear, 
- with `[ez_toc_shortcode]` the shortcoe just appears on the page, but doesn't render the table of content.

Is it possible to enable support of WooCommerce category description and display EToC there?

**Comment by Zabi09** [comment]
Pushed in 2.0.29

**Comment by Sanjeevsetu** [comment]
This fix causes problems for other users. It adds empty toc container for Woocommerce Archive Description.

Ref: https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/377.

I am re opening it and would properly fix it
