### ISSUE TITLE
Conflicts with WP-Typography

### ISSUE THREAD

**Issue by bdeshi** [ahmedkaludi/Easy-Table-of-Contents#135]
the [WP-Typography](https://wordpress.org/plugins/wp-typography/) plugin adds invisible special characters inside post content to assist with readability.

Easy-Table-Of-Contents is unable to create anchor spans for headings modified by WP-Typography.

For example, the simple heading text "**1919 translation by H. Rackham**" may be rendered by wp-typography as:
```
<h2>1919 trans&shy;la&shy;tion by H. Rackham</h2>
```
Easy-table-of-contents is now unable to link this heading. An entry is created in the TOC though, but the anchor is missing.

---

If I disable wp-typography, and _manually_ add those special characters into the heading while typing up the post, _then_ the table-of-contents works fine. However, the special characters should probably be filtered out of the created link:
```
<h2>
  <span class="ez-toc-section" id="1919-trans%c2%adla%c2%adtion-by-h-rackham"></span>
  1919 trans&shy;la&shy;tion by H. Rackham
  <span class="ez-toc-section-end"></span>
</h2>
```

**Comment by Zabi09** [comment]
Pushed in 2.0.30
