### ISSUE TITLE
Feature request: wysiwyg button to insert TOC

### ISSUE THREAD

**Issue by jeremy-saidani** [ahmedkaludi/Easy-Table-of-Contents#140]
Hey,

First, thank for the plugin and all the work you've done !
I'm wondering if it is possible to add a feature : a button in the wysiwyg editor witch add the shortcut `[ez-toc]`
Is it possible ? Can I do it myself with some code ?

Thx
Jérémy

**Comment by Zabi09** [comment]
Pushed in 2.0.30

**Comment by jeremy-saidani** [comment]
Perfect thank you !
