### ISSUE TITLE
Smooth Scroll Offset

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#143]
Issue when smooth scroll offset does not always work.

@link https://wordpress.org/support/topic/smooth-scroll-offset-not-working-2/
@link https://wordpress.org/support/topic/php-8-0-and-smooth-scroll-offset/

Possible solution:

@link https://wordpress.org/support/topic/smooth-scroll-offset-not-working-2/#post-13553228

Also, investigate using CSS only. Example:

``` CSS
#container {
	scroll-behavior: smooth;
}```

However, this will not properly deal with offsets required because of sticky headers.

**Comment by muslimakhan** [comment]
User report for issue after this ticket resolved:

https://wordpress.org/support/topic/back-to-top-button-does-not-work-correctly-in-generatepress-in-version-2-0-40/

**Comment by sajandara** [comment]
A user is facing the same issue.
https://magazine3.in/conversation/82868?folder_id=27

**Comment by Sdaud1950** [comment]
A user is facing the same issue.
https://magazine3.in/conversation/85489?folder_id=29
