### ISSUE TITLE
While using TOC with Elemontor does not work with links that contain a special character.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#150]
While using TOC with Elemontor, it does not work with links that contain a special character.

Ref Ticket: https://secure.helpscout.net/conversation/1831225822/234320?folderId=6406109

Ref screenshot: https://prnt.sc/YMkkyYiZ0POO

**Comment by syedimran22** [comment]
Released in Easy Table of Content Version : 2.0.19
