### ISSUE TITLE
Need to load CSS/JS files only on the selected post types.

### ISSUE THREAD

**Issue by saurabhpandey542000** [ahmedkaludi/Easy-Table-of-Contents#154]
Need to add the JavaScript and CSS are not loading on some specific selected post types,

Here is the referral link: --

https://secure.helpscout.net/conversation/1840578969/236040?folderId=6541793

**Comment by syedimran22** [comment]
Released in Easy Table of Content Version : 2.0.19

**Comment by cbsa100** [comment]
now the css&JS only load if its inserted automatically
when i insert it via theme files it doesnt load them
