### ISSUE TITLE
Add New Functionality "sidebar placement option"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#156]
Ref Ticket: https://secure.helpscout.net/conversation/1844802689/236802?folderId=6406109

 placement option in the sidebar so that users can add to the sidebar.

**Comment by Zabi09** [comment]
You can add the TOC with this widget in the sidebar - https://prnt.sc/e4xFY0aO9tGW and also you can add the TOC with this shortcode – [ez-toc] and with the help of this you can easily add the TOC in the sidebar or anywhere in the WordPress
