### ISSUE TITLE
Need to fix the issue related to Font size of Heading and sub-heading

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#161]
When we put font size above 100% then subheading becomes larger than main headings and when it is 100% they become of similar size and when we put size less than 100%, subheading becomes smaller than main headings. Also recreated on localhost.

Help scout URL -:  https://secure.helpscout.net/conversation/1856472743/238836?folderId=1060556

Reference image below 100% -: 
![Screenshot (383)](https://user-images.githubusercontent.com/78167698/164892446-67944732-e453-4f58-9b1c-71c1aac9df44.png)
Reference image above 100% -: 
![Screenshot (384)](https://user-images.githubusercontent.com/78167698/164892511-5b069d0c-7bb5-4a7e-891f-24621ccaa1a2.png)
Reference image at 100% -: 
![Screenshot (385)](https://user-images.githubusercontent.com/78167698/164892545-b9e88d62-b2d9-46b4-a523-14d107eb1a53.png)

**Comment by ahmedkaludi** [comment]
This is a part of upskill and will be assigned to Naser.

**Comment by Zabi09** [comment]
Pushed in 2.0.25
