### ISSUE TITLE
ETOC not jumping in some posts.

### ISSUE THREAD

**Issue by DeheemB** [ahmedkaludi/Easy-Table-of-Contents#163]
Ticket: https://secure.helpscout.net/conversation/1852795875/238241?folderId=6406114

It does not jump when clicked on ETOC in new posts.

Working URL: https://plussizebirth.com/plus-size-pregnancy-gifts/
Screenshot reference: https://prnt.sc/vvSsRulw6llY

Issue URL: https://plussizebirth.com/third-trimester-plus-size-pregnancy/
Screenshot reference: https://prnt.sc/veMGT7AWkl0l

**Comment by Zabi09** [comment]
Pushed in 2.0.20
