### ISSUE TITLE
Need to add new functionality ("Hide some topics from table of contents")

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#164]
The user wants to hide some topics from the table of content, e.g. Hide some of the H2 headings from all the H2 headings

Ref ticket: https://secure.helpscout.net/conversation/1860231146/239264?folderId=1060556

**Comment by Sdaud1950** [comment]
Need Same functionality for this user also.
https://secure.helpscout.net/conversation/1858720827/239149?folderId=6370795

**Comment by Zabi09** [comment]
Fixed in https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/151

**Comment by Zabi09** [comment]
Pushed in TOC PRO -  1.0.1
