### ISSUE TITLE
Feature Request: Modify URL Anchor - Add new Filter ("ez_toc_url_anchor_target_before" in ezTOC_Post->generateHeadingIDFromTitle())

### ISSUE THREAD

**Issue by camya** [ahmedkaludi/Easy-Table-of-Contents#167]
# Problem - Modify URL Anchor, filter applied too late!

At the moment, It's not easy to sanitize the generated URL Anchor.

There is a filter named `ez_toc_url_anchor_target` (found in `ezTOC_Post->generateHeadingIDFromTitle()`), but this applies **AFTER** any change has been applied to the hash already.

There is a filter missing, which is applied **BEFORE** the anchor is modified, e.g. `ez_toc_url_anchor_target_before`.

# Solution - New filter "before" (ez_toc_url_anchor_target_before)

Add the filter `ez_toc_url_anchor_target_before` at the beginning of `ezTOC_Post->generateHeadingIDFromTitle()`.

```
private function generateHeadingIDFromTitle( $heading ) {

    $return = false;

    if ( $heading ) {

       $heading = apply_filters( 'ez_toc_url_anchor_target_before', $heading );

       // Original implementation starts here...

        $return = html_entity_decode( $heading, ENT_QUOTES, get_option( 'blog_charset' ) );
            
       // ...

    }

    return apply_filters( 'ez_toc_url_anchor_target', $return, $heading );
}
```

# Example Filter

This allows something like this.

```
add_filter('ez_toc_url_anchor_target_before', static function ($heading) {

	$heading = strip_tags($heading);
	$heading = str_replace('Unwanted Text', '', $heading);
	$heading = sanitize_title($heading);

	return $heading;
});

```

**Comment by Zabi09** [comment]
Pushed in 2.0.23
