### ISSUE TITLE
Can't escape special characters in alternate titles

### ISSUE THREAD

**Issue by J-B-G** [ahmedkaludi/Easy-Table-of-Contents#170]
Hi, any special character such as single, double quotes or accents aren't parsed by the alternate title section, and eztoc ignores customization on those items.

Steps to replicate 

1. Create post with H2 containing special character – Ex: This ain't working
2. Add alternate title in the corresponding section – Ex: This ain't working|This is not working
3. Notice the title is not updated in the TOC

Any help appreciated on this. Workarounds (other than not using special characters...) welcome!

**Comment by Zabi09** [comment]
I have tested it on multiple websites, but I cannot recreate it - https://prnt.sc/mooH5rbonMhL and it's working fine. Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
