### ISSUE TITLE
TOC Toggle is not working on mobile version with Magnolia Theme

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#174]
While using the Magnolia Theme toggle is working in Dekstop but the issue is on the Mobile version as the toggle is visible but not working.

Recreate steps
1) Download the Theme
2) Activate the Theme
3) Set the TOC 
4) check on the mobile version.

Ref:https://magazine3.in/conversation/4601?folder_id=29

**Comment by Zabi09** [comment]
Pushed in 2.0.24
