### ISSUE TITLE
Need to add a new functionality "shrink the width to the size of title when hidden"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#176]
Shrink the width to the size of the title when hidden and expand it to the size of the headings when showing it.

Ref ticket: https://magazine3.in/conversation/4680?folder_id=27

Ref Video: https://monosnap.com/direct/fqz7MayAoMw6Gpz7kdWUzyFbu2MWvv

**Comment by Zabi09** [comment]
Pushed in TOC PRO -  1.0.1
