### ISSUE TITLE
Need to add Custom Sticky Gaping option

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#186]
A user has a sticky header and when he clicks on the link in TOC then he redirects to the heading but the heading and some content get hidden by the sticky header.

Reference Ticket -: https://magazine3.in/conversation/4837?folder_id=23

**Comment by Zabi09** [comment]
If you are using a sticky header then you need to add this CSS and that will fix your issue.

`.entry-content *[id]:before { 
    display: block; 
  content: " "; 
  margin-top: -75px; 
  height: 75px; 
  visibility: hidden; 
}`
