### ISSUE TITLE
Conflict issue with ezoic plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#188]
Freescout URL:- https://magazine3.in/conversation/4696?folder_id=21

Description:-
When the user activates the ezoic plugin, ETOC is hidden behind the ads which the user adds with the help of the ezoic plugin.

Issue Video:-
https://monosnap.com/direct/9QQ0T1WqGUWxpVyc5Dj7e4d2eqakRn

**Comment by Zabi09** [comment]
Pushed in 2.0.25
