### ISSUE TITLE
Need to improve "Web Accessibility" in TOC Toggle.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#190]
RER free scout:https://magazine3.in/conversation/6227?folder_id=29

Need to create new functionality in TOC Toggle, where we can show the content in TOC Toggle.
REf video:https://www.loom.com/share/0cd6c582f25c46fe9cd4530ca45869a4

**Comment by Zabi09** [comment]
Pushed in 2.0.25
