### ISSUE TITLE
502 Bad gateway error

### ISSUE THREAD

**Issue by FrugalNavyWife** [ahmedkaludi/Easy-Table-of-Contents#191]
I installed TOC yesterday and now i have select posts on my website that I cannot view on the live side. I get the 502 Bad gateway Error. I have contacted hosting and they said it was due to TOC plugin conflict. I haven't found another post that its conflicting with mainly just this one. Any ideas on how to fix this? I am not tech savvy enough to dig into the coding.

**Comment by ahmedkaludi** [comment]
just contact us from https://tocwp.com/contact/ and we will converse on there
