### ISSUE TITLE
TOC Loading Method Pure Css Problem

### ISSUE THREAD

**Issue by LucifaEx** [ahmedkaludi/Easy-Table-of-Contents#194]
After last TOC update I'm facing this issue. There is a issue with css file. When I hide table of content It's become look like this.

![Screenshot_20220613-202616](https://user-images.githubusercontent.com/107417510/173376571-fce89bd5-0fb3-494e-97a2-ef0fac3d3f5a.png)

any solution to fix it? I'm also facing this issue on my other sites. live - [https://www.statusify.xyz/celeder-koster-status/](https://www.statusify.xyz/celeder-koster-status/)

Please note that, I'm not using any plugin which can break css file. Like css/html minify, cache plugin etc...

**Comment by Zabi09** [comment]
Pushed in 2.0.24.1
