### ISSUE TITLE
Issues related to latest update: Toc not displaying properly

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#195]
https://wordpress.org/support/topic/new-version-breaks-plugin/
https://wordpress.org/support/topic/toc-not-showing-before-first-heading/
https://wordpress.org/support/topic/toggle-view-option-causes-toc-disappeared-after-upgrading-to-new-version/
https://wordpress.org/support/topic/toc-loading-method-pure-css-problem/

**Comment by sajandara** [comment]
Similar issue with other users as well.

https://magazine3.in/conversation/8104?folder_id=27
https://magazine3.in/conversation/8118?folder_id=27
https://magazine3.in/conversation/8133?folder_id=27
https://magazine3.in/conversation/7994?folder_id=4

**Comment by Zabi09** [comment]
Pushed in 2.0.24.1
