### ISSUE TITLE
Shortcodes are not rendering in TOC titles

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#197]
Reference screenshot: https://prnt.sc/iBnKwY5KqZmu
Reference ticket:
https://wordpress.org/support/topic/toc-not-showing-before-first-heading/

**Comment by andrea-calligaris** [comment]
Actually, in my case, the whole table of content is not displayed at all, after updating to the last version.

**Comment by Zabi09** [comment]
Pushed in 2.0.25
