### ISSUE TITLE
TOC loading method should be same for CSS and JS

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/Easy-Table-of-Contents#199]
Currently, the toggle button is different check the below Screenshot
Loading Method CSS: https://monosnap.com/file/3d1m8ffceAR75lXTlJOWgzUi8jqors
Loading Method JS: https://monosnap.com/file/A4TfASxTG2LjBlQFjG4Kf3FNy72p6F

Both toggles should same.

**Comment by Zabi09** [comment]
Pushed in 2.0.26
