### ISSUE TITLE
Need to add a new functionality so that "headings should get highlight while scrolling through the content"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#203]
The headings should get highlighted while scrolling through the content.

Ref Ticket: https://magazine3.in/conversation/4769?folder_id=27

**Comment by Zabi09** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/issues/8

**Comment by Zabi09** [comment]
Pushed in TOC PRO -  1.0.1
