### ISSUE TITLE
Hiding H3s while showing H2s?

### ISSUE THREAD

**Issue by johnstonesnow** [ahmedkaludi/Easy-Table-of-Contents#204]
I am yet to find a plugin that can do this so I thought I would ask if it's possible with Easy ToC - 

I have articles with 5-15 H2s, and each H2 has around 5-10 H3s underneath. I would like to auto show the H2s, so there's a visible ToC (for Google and users to see the main topics of the articles), but if i include the H3s the list is huge and needs two to three page scrolls to get to the content! 

Is there any way to make the H2s show (click to hide), but the H3s hide (click to show)?!

Thanks

**Comment by Zabi09** [comment]
Github is for tried and tested bugs. for support please create a ticket for this on https://tocwp.com/contact/
once it's verified by our technical team, then we will re-open or create a bug report.
