### ISSUE TITLE
While using the WP Bakery page builder, in the custom heading module, TOC is not working.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#205]
Ref;https://magazine3.in/conversation/9544?folder_id=29
ref screenshot;https://prnt.sc/OflrhcCUJ97N

While using the WP Bakery page builder, while using the custom heading module, Toc is not showing in the heading.

Recreate Steps:
1) Install the Wp-bakery  page builder
2) Create a Custom heading module.

**Comment by Zabi09** [comment]
Pushed in 2.0.26

**Comment by 77naveenop** [comment]
New user - : https://magazine3.in/conversation/36627?folder_id=23

When we click on any heading of the TOC in the mobile version, it redirects to the top of the page instead of the heading.
