### ISSUE TITLE
Toc does not work in the Avada themes in widgets for the left sidebar.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#206]
Ref https://magazine3.in/conversation/9596?folder_id=29

In the Avada theme, TOC is not working in the widget on the left sidebar. From Version 2.0.24.1, when we roll back the plugin to Version 2.0.19, it works.

Ref video:https://www.awesomescreenshot.com/video/9582360

**Comment by Zabi09** [comment]
Pushed in 2.0.26
