### ISSUE TITLE
salient core plugin conflict with last update 2.0.24.1

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#207]
Freescout:- https://magazine3.in/conversation/9519?folder_id=21

Description:-
A user adds the h2 heading with the help of a salient core plugin. but the latest update H2 heading had disappeared from the table.

Issue screenshot:-
https://prnt.sc/h4qC4RyEEQEg with version 2.0.24.1 ( facing issue with this version)
https://prnt.sc/d9mZp6evITVX with version 2.0.19  ( working perfectly with this version)

**Comment by Zabi09** [comment]
Pushed in 2.0.25
