### ISSUE TITLE
Headers in content of shortcodes are not getting picked up

### ISSUE THREAD

**Issue by WegzOffbeat** [ahmedkaludi/Easy-Table-of-Contents#209]
I am using a shortcode that displays a FAQ , and the title of that section used to get picked up by the plugin, it stopped on its own now.

**Comment by Zabi09** [comment]
@WegzOffbeat We have fixed this issue in 2.0.25.1, Will you please update it and let us know

**Comment by Zabi09** [comment]
Pushed in 2.0.26
