### ISSUE TITLE
broken for non-English titles (2.0.23 was the last working)

### ISSUE THREAD

**Issue by alex29ua** [ahmedkaludi/Easy-Table-of-Contents#211]
There's an issue with all versions after 2.0.23 for some non-En titles not being "clickable" in the TOC. Those aren't getting their "span id=" in the content - but they still appear in the TOC, just don't scroll anywhere. 
It only happens to titles written in Ukrainian or russian text and only with titles having short words of 1-2 letters in them. If all words are longer than 2 letters, it works ok. So I have a mix of working and broken items in the page's TOC. 

Please check.

**Comment by alex29ua** [comment]
Tried DEBUG mode, here's the output for the Found and Replace with sections for two titles, first doesn't work, second works in the TOC

```
>И на том спасибо</h3>
>Три конверта</h3>
```

```
><span class="ez-toc-section" id="%D0%98_%D0%BD%D0%B0_%D1%82%D0%BE%D0%BC_%D1%81%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE"></span>И на том спасибо<span class="ez-toc-section-end"></span></h3>
><span class="ez-toc-section" id="%D0%A2%D1%80%D0%B8_%D0%BA%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0"></span>Три конверта<span class="ez-toc-section-end"></span></h3>
```

However, in the rendered page the first <h3> remains "pure", without span inserted.

**Comment by alex29ua** [comment]
Aha! I finally got it!!
The issue is the cooperation between your plugin and " [ram108] Web Typography Standards" plugin.
Typography plugin modifies short words (1-2 letters) to have `&nbsp;` after them so they stay on the same line together with the next word.
The modified content looks like this:
```
<h3 id="5"><span class="ez-toc-section" id="%D0%9B%D1%8E%D0%B1%D0%BE%D0%B2%D1%8C_%D0%B4%D0%BE_%D0%B3%D1%80%D0%BE%D0%B1%D0%B0"></span>Любовь до&nbsp;гроба<span class="ez-toc-section-end"></span></h3>
```
(note the `&nbsp;`). Version 2.0.23 of Easy TOC was probably having its hook somewhere before that plugin and was correctly inserting the anchors.
Version 2.0.24 and higher is not picking this up, I only have this in the content
```
<h3 id="5">Любовь до&nbsp;гроба</h3>
```
Can you reproduce it?

**Comment by Zabi09** [comment]
Pushed in 2.0.26
