### ISSUE TITLE
Warning while using the pro version with the parent plugin.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#212]
Warning while using the pro version with the parent plugin.
Warning: Invalid argument supplied for foreach() in /home/customer/www/vitality-pro.com/public_html/wp-content/plugins/easy-table-of-contents/includes/class.post.php on line 372

Ref ticket: https://magazine3.in/conversation/12496?folder_id=27

Ref screenshot: https://prnt.sc/VaOtWyL6amBo

**Comment by Zabi09** [comment]
Pushed in 2.0.27
