### ISSUE TITLE
There is a PHP compatibility issue with TOC for PHP version 7.3.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#213]
REf:https://magazine3.in/conversation/11660?folder_id=29

There is a PHP compatibility issue with TOC for PHP version 7.3. While testing with the PHP Compatibility Checker plugin, it shows an error.
screenshoot Ref: https://www.awesomescreenshot.com/image/29375405?key=3a8acf8279010f664f8279ffef5247e0

**Comment by Zabi09** [comment]
https://wordpress.org/support/topic/php-compatibility-issue-5/

https://wordpress.org/support/topic/php-compatibility-issues-3/

**Comment by Zabi09** [comment]
Pushed in 2.0.27
