### ISSUE TITLE
Form elements do not have associated labels In lighthouse report

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#219]
Screenshot of the issue: https://prnt.sc/_eU4ucgL7IU4
Issue URL: https://decimaltohex.com/
Reference ticket: https://wordpress.org/support/topic/form-elements-do-not-have-associated-labels-7/

**Comment by Zabi09** [comment]
Pushed in 2.0.28

**Comment by NXPFatur** [comment]
I have the same problem with Version 2.0.50.

Screenshot : https://prnt.sc/BaEiii9cpVOk
