### ISSUE TITLE
 When a user adds the shortcode on the product page while using the  Woocommerce plugin, TOC does not show.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#224]
1.When a user adds the shortcode on the product page while using the Wommerce plugin, TOC does not show.

2.In some cases, The TOC shows, but it does not redirect to the article after clicking on it.

Ref.video.
https://www.awesomescreenshot.com/video/10017493?key=4e31ab3f66fea565eb2f214f96b2c649
 
Ref. https://magazine3.in/conversation/17540?folder_id=29

**Comment by Zabi09** [comment]
Pushed in 2.0.30
