### ISSUE TITLE
Need to add option to select which Tag's ( h2, h3 or h4 ) heading to show.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#225]
Currently, we can choose to show only H1, H2, H3, etc. But what users want to do is to INCLUDE H2, H3, and H4 in my ToC, BUT only by default SHOW the H2s and allow users to CLICK TO OPEN/SHOW the H3 and H4s.

Reference ticket -: https://magazine3.in/conversation/16194?folder_id=4

**On hold due to unavailability of any reference.**

**Comment by ahmedkaludi** [comment]
Since we don't have a practical scenario, We are forced to close the ticket.

We can't build features based on assumptions.
