### ISSUE TITLE
After 2.0.27 version updates making conflict with Avada theme

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#229]
User adding TOC using shortcode and In 2.0.27, it was working well but after 2.0.28 updates, it breaks the site and when rolling back to version 2.0.27 it is working fine.

Reference ticket -: https://magazine3.in/conversation/9167?folder_id=23

Reference screenshot -: 
![image](https://user-images.githubusercontent.com/78167698/181184011-27019a2c-a14e-477b-8a31-1a8543561697.png)

**Comment by Zabi09** [comment]
Pushed in 2.0.31.1
