### ISSUE TITLE
Need to fix Easy table of content in sidebar.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#232]
Reference URL:-
https://magazine3.in/conversation/15899?folder_id=21

Description:
The issue is fixed on the previous ticket #220 but needs to do some changes in the table of content.

Issue video:
https://monosnap.com/direct/UNq21maThh4juO6i9NRyrlQOSuEcAQ

**Comment by Zabi09** [comment]
Pushed in 2.0.31.1
