### ISSUE TITLE
Last version of Easy-Table-of-Contents causes problems by updating my latest post

### ISSUE THREAD

**Issue by steinba8668** [ahmedkaludi/Easy-Table-of-Contents#234]
I experienced today issues with the last post in combination with the Easy-Table-of-Contents plugin on my Wordpress.com blog. The post cannot be opened again in the Gutenberg editor. I always get a 507 error message (timeout). 

When I disable the the Easy-Table-of-Contents plugin then I can open it again in the Gutenberg editor immediately. I guess this issue came up in combination with your latest update 13 hours ago.

**Comment by Zabi09** [comment]
@steinba8668 Are you using the latest version 2.0.31 and still having this issue? Please let me now

**Comment by steinba8668** [comment]
Hi Ahmed, 

I must admit that I looked for a quick resolution and switched to TOC+.

This morning I deactivated TOC+ and activated Easy-Table-of-Contents for a quick check. Version 2.0.31 is installed and I opened the blog post for editing. It worked fine for me. No more timeouts.

Best regards,

Andreas!

Von meinem neuen iPad Pro gesendet 😄
