### ISSUE TITLE
While using the TOC with Elementor, the animation content is not showing up on the user's website. ("END USER PROBLEM")

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#237]
While using the TOC with Elementor, the animation content is not showing up on the user's website. When we roll back the plugin to the 2.0.27 version, then it works fine. problem with the most recent version.

Before Toc was active.
 https://prnt.sc/fxPrOBce81Z6

After TOC is active..
https://prnt.sc/Lgy2NQhXqFiz

Ref tickets.  https://magazine3.in/conversation/22041?folder_id=29

**Comment by Zabi09** [comment]
Pushed in 2.0.31.1
