### ISSUE TITLE
Sticky Toggle

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Easy-Table-of-Contents#241]
A new feature which will look like this: (message me on Telegram for the demo)

- [x] primary feature (free)
- [ ] option to change left, right, top, bottom [pro] 
- [ ] font size [pro]
- [ ] background & Text color [pro]
- [ ] width  [pro]

**Comment by Zabi09** [comment]
- [ ] When I am closing the main toc toggle then sticky toc is also getting close - https://prnt.sc/kS8POrHi8h4G

- [ ] Can you please rename this "index" text to something meaningful or create an option to change this text or the user can change it accordingly - https://prnt.sc/KThJ5OFB9id7

- [ ] Not able to change the width and height of the sticky when I change the value then it takes the default only - https://gifyu.com/image/ST8Pf

- [ ] Sticky functionality not working when CSS loading method is selected

**Comment by Zabi09** [comment]
Pushed in 2.0.32
