### ISSUE TITLE
TOC stopped working after updated

### ISSUE THREAD

**Issue by juniorbra** [ahmedkaludi/Easy-Table-of-Contents#247]
I updated the plugin and it just disappeared from my site.

**Comment by Zabi09** [comment]
@juniorbra Are you using the latest version 2.0.31.1 and still having this issue? Please let me now

**Comment by juniorbra** [comment]
> @juniorbra Are you using the latest version 2.0.31.1 and still having this issue? Please let me now

Hi, when saving again, the problem was fixed. Thanks

**Comment by Zabi09** [comment]
Pushed in 2.0.32
