### ISSUE TITLE
Getting critical error on front end after activating the Easy table of Content Pro extension when " Easy table of Content " is deactivated.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/Easy-Table-of-Contents#249]
Getting critical error on front end after activating the Easy table of Content Pro extension when " Easy table of Content " is deactivated.

ref video - https://monosnap.com/direct/nKaSvwkum2BFhhQlA9XKddWhcH7iuz

ref ticket - https://magazine3.in/conversation/25241?folder_id=4

**Comment by Zabi09** [comment]
Fixed in https://github.com/ahmedkaludi/easy-table-of-contents-pro/issues/14
