### ISSUE TITLE
Need to fix the sidebar position

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#251]
Freescout:-https://magazine3.in/conversation/26309?folder_id=21

Description:-
A user adds the Easy table of content in the sidebar. but when the user down the table of content shown in the footer.

Issue Screenshot:-
https://prnt.sc/nWOtHQYk0lqZ

**Comment by Zabi09** [comment]
Pushed in 2.0.32
