### ISSUE TITLE
Need to make a feature of capitalizing the first letter of each title in the table of content.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#252]
Freescout:- https://magazine3.in/conversation/26624?folder_id=21

Description:-
User want a feature where every first letter of a title should be capitalized in the table of content.

**Comment by Lumieredelune** [comment]
HI you can do it with very simple css : 

text-transform:capitalize

**Comment by Zabi09** [comment]
If the title in the content is capitalized then the TOC title will also be capitalized by default but if your main title is not capitalized and you need to make only the TOC title capitalized then you can simply add this CSS into custom CSS section of your customizer and that will fix your issue.

`#ez-toc-container ul {
    text-transform: capitalize;
}`
