### ISSUE TITLE
TOC is not working on category page

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#260]
To add TOC to the category page, there is no option to auto-insert there and if we are adding via shortcode then it is not working.

Reference screenshot ( how adding shortcode ) -: https://monosnap.com/direct/qQfUfCaJ2lnImBHlrpdYtzH5jldHgM

Reference ticket -: https://magazine3.in/conversation/29751?folder_id=23

**Comment by Zabi09** [comment]
Going to get fixed in - https://github.com/ahmedkaludi/easy-table-of-contents-pro/issues/7
