### ISSUE TITLE
Table of Contents Jump links not working

### ISSUE THREAD

**Issue by nosfatsug** [ahmedkaludi/Easy-Table-of-Contents#268]
Hello – just installed and setup. The TOC appears on every page. The TOC links do not function. I use WP Rocket and have included the “/easy-table-of-contents/assets/js/front.min.js” entry for the delay javascript execution compatibility exclusions as recommended by WP Rocket with the Easy Table of Contents plugin. I’ve cleared all cache for WP Rocket, Kinsta, and Cloudflare. I've tried updating my permalinks (resaved) which sometimes fixes things. Not sure what to attempt next.

uraniumstockinvesting.com is my site - again, the table of contents appears on all pages - but clicking them doesn't take me down the page to the appropriate areas.

Thank you in advance for your help!

**Comment by nosfatsug** [comment]
Since posting above, I've deactivated WP Rocket, and received the same result after clearing all cache.

**Comment by ahmedkaludi** [comment]
@nosfatsug 

Github is for valid and re-creatable bugs, for technical support kindly contact us on https://tocwp.com/contact/
