### ISSUE TITLE
Elementor Widget

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#27]
Hello, as a test, I created a little example ‘hello world’ Elementor widget so Easy Table of Contents can be used by people using Elementor in a more user friendly way.

Elementor is a very popular WordPress page builder (600.000+ active installations) https://wordpress.org/plugins/elementor/

Easy Table of Contests works in Elementor through Elementors Shortcode plugin, but the Shortcode route doesn’t seem to be the most content editor friendly solution.

@shazahm1hotmailcom, you’ve expressed concerns about Shortcodes in that regard too
https://wordpress.org/support/topic/ez-toc-or-toc-doesnt-display-anything/#post-9982200

I’ve put the example plugin at
https://github.com/silkogelman/elementor-easy-table-of-contents

It currently does not fully work (it’s not inserting a real ezTOC, but it shows a bit of what an Easy Table of Contents Widget could look like for the end-user, the people creating content with Elementor.

Basically it allows them to drop the ‘Easy Table of Contents widget’ in their content, and allow them to configure it like with the Table of Contents metabox in the regular WordPress editor screen.

Install / test instructions:
– Activate Easy Table of Contents plugin
– Activate Elementor plugin
– Activate elementor-easy-table-of-contents plugin (code at GitHub)

– edit a page with Elementor
– search for ‘Easy’ in the widgets
– drop that ‘Easy Table of Contents’ widget in a section
– look at the sample editing options on the left

It currently can’t do more than that. It serves the goal of showing the potential as a content editor user friendly widget.

I hope you like this idea of making Easy Table of Contents availably to content editors in a more user friendly way.

And I’m hoping you’d be willing to consider creating a fully working Elementor add-on for Easy Table of Contents that is shipped with Easy Table of Contents.
I believe it will add value to the Easy Table of Contents plugin, as it makes creating a Table of Contents available to over half a million content editors.

I’d be happy to help develop the idea / help test it, etc. (I’m not a great coder)

kind regards,
Sil

**Comment by shazahm1** [comment]
tagging @silkogelman

**Comment by shazahm1** [comment]
@silkogelman 

For some reason you post at wp.org disappeared... So I copied the contents of my email notification here so it is not lost.

**Comment by silkogelman** [comment]
Thank you @shazahm1 ! 
It was held for moderation, I think it should be visible now at
https://wordpress.org/support/topic/elementor-widget-for-easy-table-of-contents-plugin/
Also, I linked it back to this GitHub issue.

## Widget Screenshots
Here are two screenshots to get an idea of what an Easy Table of Contents Elementor widget could look like:
![elementor-easy-table-of-contents-widget](https://user-images.githubusercontent.com/25695655/37697642-40a3536a-2cde-11e8-915a-35664537e27a.png)
![elementor-easy-table-of-contents-widget-configuration](https://user-images.githubusercontent.com/25695655/37697650-4d239fa0-2cde-11e8-80bb-9c806cdc807e.png)

**Comment by shazahm1** [comment]
Would you be willing to put more work into this to make it more fully working?

**Comment by silkogelman** [comment]
As stated in my original post: I’d be happy to help develop the idea / help test it, etc.

I’m not a great coder, so realizing the integration with Easy Table of Contents would require me to invest an amount of time that I unfortunately don't have.

**Comment by dbjpanda** [comment]
@silkogelman Here is one [TOC plugin](https://github.com/dbjpanda/kb-elementor) purely created for Elementor.

**Comment by UnknownGuy123** [comment]
Has this been every considered again?

**Comment by shazahm1** [comment]
yes, I'll be adding it as a commercial/premium addon. I first need to complete the rewrite which is going very slowly, no eta.

**Comment by Zabi09** [comment]
Added in Easy TOC PRO
