### ISSUE TITLE
Shortcode are not working with Salient theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#271]
Freescout:-https://magazine3.in/conversation/33229?folder_id=21

Description:-
The user uses the salient theme and wpbakery page builder plugin in that he uses the global section feature. Shortcodes are working well in pages that are created by the global section option. Inside the page, he creates some posts under which he creates sub posts and inserts the short codes, but the short codes are not working in those sub posts.

Issue URL:-
https://uniscopio.com/universidad/ie-university/

Issue Screenshot:-
https://prnt.sc/O6Y7ojD3dzm-

**Comment by muslimakhan** [comment]
We have finished this issue but this theme have not implement our Easy TOC design and we have already given so much time to debug this issue therefore we will do this issue in the next milestone.
