### ISSUE TITLE
Audit the PRO version

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Easy-Table-of-Contents#277]

**Comment by akshaywali** [comment]
- [ ] Incorrect links in tabs 
- [ ] Shrink the width what is this ??
- [ ] Add documentation link 
- [ ] Fixed TOC proper option with alignment and gaps (drag and drop feature)
- [ ] Make sure Fixed TOC is responsive on mobile

**Comment by akshaywali** [comment]
- [ ] TOC shows on reload even if is closed , if its closed then it should be closed even on loading

**Comment by ahmedkaludi** [comment]
it will be a part of 1.0.2 PRO version

**Comment by muslimakhan** [comment]
3. Add documentation link 
This point is working on due to support team making documentation on it, it refer to :
https://github.com/ahmedkaludi/easy-table-of-contents-pro/issues/21
