### ISSUE TITLE
Problem with TOC on mobile

### ISSUE THREAD

**Issue by onemillionplaces** [ahmedkaludi/Easy-Table-of-Contents#284]
Hi,

since one of the last updates TOC no longer runs as usual on mobile. When I open a [blog post](https://one-million-places.com/usa/florida-jungle-island-miami) on mobile (Samsung Phone S20 with Android) and scroll with my finger over the TOC module, it automatically jumps somewhere without me explicitly pressing the link in the table of contents.

Can you reconstruct this behavior?

It always worked before. Attached is a small screen recording. The jump happens without clicking any link - it happens during scrolling over the TOC.

Michael

https://user-images.githubusercontent.com/67807397/189525404-9568da70-5e15-4968-877b-c94eefe755c5.mp4

**Comment by muslimakhan** [comment]
Hey @onemillionplaces ,

Your mobile screen touch issue is from other cornerstone wp plugin on touch screen devices, here custom JavaScript code is written by plugin or your developer:
```js
jQuery( function($){
  $(document).on('touchstart click', '.ez-toc-link',  function( e ) {
    var ID = $(this).attr('href');
    e.preventDefault();
    $('html, body').animate( { scrollTop : $(ID).offset().top - 90  }, 'linear' );

    //console.log($(ID).offset().top);
  });
});
```
Screenshot: https://prnt.sc/sSTuvc2xoYIK

Plugin URL: https://wordpress.org/plugins/cornerstone/

Check with this touchstart js example:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_touchstart

You have to remove this custom JS code or remove only `touchstart` in this custom JS code for touch screen devices.

Hope it will be resolved this issue on your end, please let us know your feedback.

Thanks

**Comment by onemillionplaces** [comment]
Hi,

 

thank you for your answer.

 

The code you mentioned is some extra code you send me many month before. This is why I have added this code to my Extra JS :)

I´m not sure why we added this extra code, but should I now remove it?

 

Michael

 
 

Gesendet: Samstag, 12. November 2022 um 09:26 Uhr
Von: "Muslim Ahmad" ***@***.***>
An: "ahmedkaludi/Easy-Table-of-Contents" ***@***.***>
Cc: "onemillionplaces" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ahmedkaludi/Easy-Table-of-Contents] Problem with TOC on mobile (Issue #284)


 

Hey @onemillionplaces ,

Your mobile screen touch issue is from other cornerstone wp plugin on touch screen devices, here custom JavaScript code is written by plugin or your developer:


jQuery( function($){
  $(document).on('touchstart click', '.ez-toc-link',  function( e ) {
    var ID = $(this).attr('href');
    e.preventDefault();
    $('html, body').animate( { scrollTop : $(ID).offset().top - 90  }, 'linear' );

    //console.log($(ID).offset().top);
  });
});


Screenshot: https://prnt.sc/sSTuvc2xoYIK

Plugin URL: https://wordpress.org/plugins/cornerstone/

Check with this touchstart js example:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_touchstart

You have to remove this custom JS code or remove only touchstart in this custom JS code for touch screen devices.

Hope it will be resolved this issue on your end, please let us know your feedback.

Thanks

**Comment by muslimakhan** [comment]
Hey @onemillionplaces ,

Yes, you should replace this code:
```js
jQuery( function($){
  $(document).on('touchstart click', '.ez-toc-link',  function( e ) {
    var ID = $(this).attr('href');
    e.preventDefault();
    $('html, body').animate( { scrollTop : $(ID).offset().top - 90  }, 'linear' );

    //console.log($(ID).offset().top);
  });
});
```
from this code:
```js
jQuery( function($){
  $(document).on('click', '.ez-toc-link',  function( e ) {
    var ID = $(this).attr('href');
    e.preventDefault();
    $('html, body').animate( { scrollTop : $(ID).offset().top - 90  }, 'linear' );

    //console.log($(ID).offset().top);
  });
});
```
Only here remove `touchstart` from code.

Thanks

**Comment by onemillionplaces** [comment]
Hi,

 

thank you. This is working.

 

But since one of the last updates I can see that TOC doesn´t jump to the correct headline - desktop an mobile.

 

You can test it for example here:

https://one-million-places.com/usa/orlando-disney-magic-kingdom-kleinkind#das-feuerwerk

 

I just noticed this behavior today, before TOC always jumped to the right headline.

Can you please help me once more to fix this?

 

Michael

 
 

Gesendet: Donnerstag, 17. November 2022 um 06:54 Uhr
Von: "Muslim Ahmad" ***@***.***>
An: "ahmedkaludi/Easy-Table-of-Contents" ***@***.***>
Cc: "onemillionplaces" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ahmedkaludi/Easy-Table-of-Contents] Problem with TOC on mobile (Issue #284)


 

Hey @onemillionplaces ,

Yes, you should replace this code:


jQuery( function($){
  $(document).on('touchstart click', '.ez-toc-link',  function( e ) {
    var ID = $(this).attr('href');
    e.preventDefault();
    $('html, body').animate( { scrollTop : $(ID).offset().top - 90  }, 'linear' );

    //console.log($(ID).offset().top);
  });
});


from this code:


jQuery( function($){
  $(document).on('click', '.ez-toc-link',  function( e ) {
    var ID = $(this).attr('href');
    e.preventDefault();
    $('html, body').animate( { scrollTop : $(ID).offset().top - 90  }, 'linear' );

    //console.log($(ID).offset().top);
  });
});


Only here remove touchstart from code.

Thanks

**Comment by muslimakhan** [comment]
Hey @onemillionplaces ,

I just checked this below link and all toc links are working well on latest version 2.0.37, please clear cache once on your end:
https://one-million-places.com/usa/orlando-disney-magic-kingdom-kleinkind#das-feuerwerk

Please check this video:
https://jmp.sh/ARsWTM9J

Let me know your feedback.

Thanks
