### ISSUE TITLE
Add compatibility with the block base theme

### ISSUE THREAD

**Issue by gulsha** [ahmedkaludi/Easy-Table-of-Contents#290]
With the use of Blog Kenzie theme ETOC is not visible on post/page

Referenced Ticket : https://magazine3.in/conversation/38358?folder_id=39

**Comment by muslimakhan** [comment]
Blog Kenzie Theme is not available to do this, need more data for resolution this ticket. We will do this ticket on future milestone.

**Comment by Sanjeevsetu** [comment]
It is a user specific issue and user is not replying us so I am closing it for now, If user replies again than ticket will be reopened again
