### ISSUE TITLE
Need to make a feature or functionality where after clicking on the link, Toc should automatically get closed.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#291]
After clicking on the TOC, it is taking on the content of the link, but there is one issue: background content is getting hidden below the TOC.

Ref ticket.https://magazine3.in/conversation/27172?folder_id=29

**Comment by micker** [comment]
Great thanks

**Comment by ahmedkaludi** [comment]
it will be a part of 1.0.2 PRO version

**Comment by micker** [comment]
Cool published ?
