### ISSUE TITLE
When the name of the Open Button Text in sticky toggle is long, the sticky toggle is not working on mobile devices.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#294]
When the name of the Header Label and  Open Button Text in the sticky toggle is long, then the sticky toggle is not working on mobile devices issue is with the Foodie Pro theme.

Ref screenshots are attached below.

Ref ticket https://magazine3.in/conversation/43226?folder_id=29 

When the name of the button is large sticky toggle is not opening
https://prnt.sc/nh9w97ZQtjXn 

When the name of the button is small sticky toggle is opening.
https://prnt.sc/vByWXNggDxYU

**Comment by muslimakhan** [comment]
This issue have different issues on this theme:

- [ ]  1. Toggle Menu is created by theme in every nav tag which is in our Easy TOC plugin containers of main, sticky toggle & widget toc containers.
      Link: https://prnt.sc/FrSwEB9LdfHz
- [ ]  2. jQuery is inserted in head by theme developer therefore our Easy TOC is not working before jQuery initiates, so we have fixed on before body tag end jquery files and theme files.
      Link: https://prnt.sc/-xbdKnR2PODt

**Comment by muslimakhan** [comment]
2. Solution: Its getting error from jquery defer loading from site ground optimizer with this foodie pro theme so we have to exclude the jquery js file from settings of site ground optimizer plugin, just like link:
    Link: https://prnt.sc/D6YSgUK4kY94
