### ISSUE TITLE
While Heading created with Divi pixel are not working.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#295]
When we are adding the headings through the Divi pixel plugin, then the headings are not working.

Recreating steps 
1. Setup the Divi Theme
2.  Download and install the Divi Pixel Plugin. 
3. Create a new heading through the module Pixel text highlighter.

Ref ticket https://magazine3.in/conversation/27172?folder_id=29

**Comment by micker** [comment]
Great thanks

**Comment by micker** [comment]
Hello did you have some news about this ?

**Comment by micker** [comment]
hello sorry to but you you, but did you have some news ?

**Comment by muslimakhan** [comment]
We are working on your issue sir
Same: https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/291

**Comment by micker** [comment]
great thanks
