### ISSUE TITLE
Not working in sidebar if Auto insert is disabled.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#297]
TOC should work individually when it's added via shortcode but when the user is adding the TOC via shortcode in the widget area in the sidebar, it's not working if the Auto Insert is disabled.

Ref ticket: https://magazine3.in/conversation/47136?folder_id=4

**Comment by sajandara** [comment]
The functionality is working correctly now but there is a new bug that we found which is, If there are multiple shortcodes then only one TOC will appear.

Ref video:  https://monosnap.com/direct/PSnCD5kv66xYkIY07qMe69p78ohrwO

**Comment by Sanjeevsetu** [comment]
This solution causes css to load unnecessary. I am reverting the solution and re opening the ticket
