### ISSUE TITLE
Need to fix Pro Settings 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#300]
When we add the license key, it still shows UPGRADE TO PRO and there is no option to switch PRO settings.

Reference screenshots - :

![Screenshot (731)](https://user-images.githubusercontent.com/78167698/191752238-7368e3a8-4e9b-4dc8-bef7-db96da750cee.png)
![Screenshot (730)](https://user-images.githubusercontent.com/78167698/191752452-294d676b-70df-48a1-975e-0841a092559b.png)

**Comment by muslimakhan** [comment]
#283 Same

**Comment by muslimakhan** [comment]
Updated in 2.0.34 Version
