### ISSUE TITLE
Enabling sticky toggle makes the other links unclickable.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#301]
Enabling the sticky toggle option makes the other links unclickable on the page/post.

Ref ticket: https://magazine3.in/conversation/49374?folder_id=27

Ref video: https://monosnap.com/direct/MfatQ6q4VB4HVsT493KFwCzM4CoJ7i

**Comment by muslimakhan** [comment]
#282 Same

**Comment by muslimakhan** [comment]
Updated in 2.0.34 Version
