### ISSUE TITLE
Not working in Persian Language.

### ISSUE THREAD

**Issue by gulsha** [ahmedkaludi/Easy-Table-of-Contents#303]
In Persian Language ETOC is not clickable.

Reference Ticket : https://magazine3.in/conversation/49397?folder_id=39

**Comment by muslimakhan** [comment]
#306 same issue now resolved

**Comment by muslimakhan** [comment]
Due to this update for fixing big issue in plugin, code is reverted:

```
== Changelog ==
= 2.0.35.2 11/02/2022 =
* BUG: Jump anchors on new headings not working after the update of last version 2.0.35
* BUG: The TOC is not showing on the sidebar of all posts with the latest update 2.0.35
```

Now it will be resolved in next future milestone.
