### ISSUE TITLE
Some bugs occurring due to a "-" in pages created with Elementor

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#306]
1. If the first heading contains a "-" then the TOC will not be visible on that page with the option "before first heading" selected.

2. If any other heading contains a "-" then TOC will be visible but the heading will not work or jump to that content.

Ref ticket: https://magazine3.in/conversation/50567?folder_id=27

Ref video: https://monosnap.com/direct/ckaPxT28oHWe7M8pKWVPEmcHVgXyVv

**Comment by muslimakhan** [comment]
Due to this update for fixing big issue in plugin, code is reverted:

```
== Changelog ==
= 2.0.35.2 11/02/2022 =
* BUG: Jump anchors on new headings not working after the update of last version 2.0.35
* BUG: The TOC is not showing on the sidebar of all posts with the latest update 2.0.35
```

Now it will be resolved in next future milestone.
