### ISSUE TITLE
Per page Table of Contents Title

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#31]
Add an option so a per post table of contents tiel header can be defined. This would have to override the global option in the settings.

ref:
https://wordpress.org/support/topic/customizing-table-of-content-header/

**Comment by shazahm1** [comment]
ref:
https://wordpress.org/support/topic/toc-labelcustom-heading-is-it-possible-in-future/

**Comment by vburlak** [comment]
Hey @shazahm1 
I've already realized for my needs but the "dirty way" by overriding ezTOC_Option class. Because it hasn't a lot of ways to customize it using only hooks and filters now.

I'll review my code and can make a PR for this feature to 2.1 milestone.
Thanks!

**Comment by Sanjeevsetu** [comment]
Hi @vburlak 

Above mentioned both the feature are now available in our latest version 2.0.61. Please try it, If you face any further issue please create new ticket or contact our support
