### ISSUE TITLE
It is making the heading to repeat when we are selecting the option "After the first paragraph."

### ISSUE THREAD

**Issue by gulsha** [ahmedkaludi/Easy-Table-of-Contents#310]
While we are selecting the option After the first paragraph it is making a paragraph/heading to repeat again.

Reference ticket:https://magazine3.in/conversation/46549?folder_id=39

Reference URL:https://worksion.com/?p=17238&preview=true#for-women

Reference video:https://monosnap.com/file/xVL7y3fJIH8wDR8ihfbaZzxSMZeiwL

**Comment by Sdaud1950** [comment]
Same issue with this user. https://magazine3.in/conversation/38324?folder_id=29
