### ISSUE TITLE
When we add the shortcode on the product category  while using the Woocommerce plugin, TOC does not show.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#311]
When we add the shortcode to add TOC in the product category of Woocommerce, the TOC does not show.

Ref freescout. https://magazine3.in/conversation/53633?folder_id=29

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
User is not replying and we are unable to re create the issue at our end so I am closing it. If issue is valid and it is re creatable than create new ticket
