### ISSUE TITLE
Alignment of TOC to the center on selected posts/pages

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#314]
User scenario:  Wants to set the table of contents to align to the center on some posts (selected) only.
Reference ticket: https://wordpress.org/support/topic/align-toc-centre-sometimes/

**Comment by bmos** [comment]
This would be very helpful.
Sometime TOC fits the page best in some alignments and sometimes others.
Something like "[ez-toc align=center]" or just adding a toggle to the edit page options would be great.
