### ISSUE TITLE
Avada theme conflicted with the sidebar widget.

### ISSUE THREAD

**Issue by gulsha** [ahmedkaludi/Easy-Table-of-Contents#315]
We have seen the strange behavior of ETOC when we select the options, it flicked either to the above or below option.

Reference Ticket:https://magazine3.in/conversation/49383?folder_id=39

Reference URL:https://www.ingigni.com/blog/brand-per-differenziarsi-distinguersi-diffondersi/

Reference Video:https://monosnap.com/file/UBXcmrfYtxA7ExZuZRKQSTJOQvAdmF

**Comment by muslimakhan** [comment]
Same: #341
