### ISSUE TITLE
Name entity should be a mandatory field while adding the TOC as a block in widget area.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#318]
If the name field is not filled then TOC will not appear if it is added as a block in the widgets.

Ref video: https://monosnap.com/direct/X9dyTYrxHjHiPERo09Z9po4YkRA29V

bug found by @muslimakhan

**Comment by muslimakhan** [comment]
As I discuss with @Sanjeevsetu sir, we cant add required validation in widget form, so I have added default value `Table of Contents` for this issue solution.
