### ISSUE TITLE
更新2.0.35 10/29/2022版本后，导致界面code组件只能显示一行了

### ISSUE THREAD

**Issue by NickTan2016** [ahmedkaludi/Easy-Table-of-Contents#326]
更新2.0.35 10/29/2022版本后，导致界面code组件只能显示一行了

**Comment by NickTan2016** [comment]
![image](https://user-images.githubusercontent.com/20123947/198839126-f7ff0654-1817-4ebd-9f24-ae84b1e4429d.png)
![image](https://user-images.githubusercontent.com/20123947/198839139-1aa6db34-866e-46cd-a1cf-5f4ee1298aff.png)

**Comment by muslimakhan** [comment]
Hey @NickTan2016 sir,

Please check with latest version 2.0.35.1 and let us know if any issue now faced by your side.

Thanks

**Comment by NickTan2016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在学习中，无法亲自回复您的邮件。我将在有空时，尽快给您回复。

**Comment by muslimakhan** [comment]
ok no issue take your time and let us know, is it resolved now or if any issue faced by your side?.

**Comment by NickTan2016** [comment]
可以展示了，但是目录展开按钮点不了
![image](https://user-images.githubusercontent.com/20123947/199022531-63cf953e-6ee4-4cde-b02e-ad77e4bb8d3a.png)

**Comment by muslimakhan** [comment]
Please change color title color in  easy toc admin panel settings:
https://prnt.sc/g0h4cI4Ywq7c
and then check.

Please do once ctrl + shift + R & ctrl + F5 for hard reload then check.

**Comment by NickTan2016** [comment]
颜色是个小问题，主要是点击不了

**Comment by muslimakhan** [comment]
Hey sir,
Thanks for update, can you check from this easy toc plugin zip link:
https://drive.google.com/file/d/1gKcw7bk4SdE1MD4eBksFMgERUUrrbQcl/view?usp=sharing

Steps:
1. Download zip file
https://prnt.sc/UR4FgwVPszdS

2. Deactivate & Delete current Easy Table of Contents Plugin from plugin page of your admin panel from your website.
https://prnt.sc/1FfZT7rIy_3L
https://prnt.sc/A9lmJsOubNT6

3. Click on Add New Plugin and upload 
https://prnt.sc/pAp6yZvkws7G

4. Click on Upload Plugin: 
https://prnt.sc/hSBxRKqfqk8E

5. Add new downloaded zip file in it & install plugin.
https://prnt.sc/BQoRIUzmktyE

6. Check now your frontend posts & pages where toc is added, and do once clear cache or ctrl + F5 & ctrl + shift + R.

Let us know your feedback once, is it working well or should be more debugging on it?

Thanks

**Comment by NickTan2016** [comment]
![image](https://user-images.githubusercontent.com/20123947/199504010-a0605602-67f0-4b2f-b157-96e46b65d9f0.png)
网站添加了这个效果，你们的图标变更后，事情起冲突了

**Comment by NickTan2016** [comment]
![image](https://user-images.githubusercontent.com/20123947/199504578-692dc327-9bb6-4595-b544-9bbf06f406f3.png)
这个开关打开后，就点不了了，没打开的话，是可以收起展开的

**Comment by muslimakhan** [comment]
Hey @NickTan2016  sir,
Sorry for the inconvenience,

Can you check once your site from this latest zip file:
https://drive.google.com/file/d/1QiNWyG7odkkR9JV453wt5cL4b8SV3PMy/view?usp=sharing

Steps:

Download zip file
https://prnt.sc/UR4FgwVPszdS

Deactivate & Delete current Easy Table of Contents Plugin from plugin page of your admin panel from your website
https://prnt.sc/1FfZT7rIy_3L
https://prnt.sc/A9lmJsOubNT6

Click on Add New Plugin
https://prnt.sc/pAp6yZvkws7G

Click on Upload Plugin:
https://prnt.sc/hSBxRKqfqk8E

Add new downloaded zip file in it & install plugin
https://prnt.sc/BQoRIUzmktyE

Check now your frontend posts & pages where toc is added, and do once clear cache or ctrl + F5 & ctrl + shift + R.

Let us know about your feedback once please, sorry for delay.

Thanks

**Comment by NickTan2016** [comment]
![image](https://user-images.githubusercontent.com/20123947/199736873-e0717ce1-9091-4536-84e9-490fe205a4e9.png)
提示这个警告

**Comment by NickTan2016** [comment]
https://chromestatus.com/feature/5726124632965120

**Comment by NickTan2016** [comment]
Learn more: This change will go into effect with milestone 109.：https://chromiumdash.appspot.com/schedule

**Comment by muslimakhan** [comment]
Hey @NickTan2016 sir,

is this related from our Easy Table of Contents plugin CSS or JS script issues? 
Send us link or screenshot where this issue it is relation with our Easy TOC plugin contents.

We have checked from our side and two user sides, that this issue was facing when Easy TOC settings would be 
1. TOC Loading Method	-> Pure CSS
2. Initial View -> [✓] Initially hide the table of contents.

Now, we have removed this bug, and we will push on WordPress plugin on next milestone.

Thanks

**Comment by NickTan2016** [comment]
https://blog.ntan520.com/article/16648 这个是网站地址，你可以看下

**Comment by NickTan2016** [comment]
目录展开按钮点不了，提是今天发的截图那错误

**Comment by NickTan2016** [comment]
请快速定位下问题，半个小时后，我将取消【最初隐藏目录】勾选项，使网站恢复正常

**Comment by NickTan2016** [comment]
OK，那等你们更新版本后，我再试下

**Comment by NickTan2016** [comment]
今天的截图，是点击不了那个问题的错误提示
