### ISSUE TITLE
Structured plugin is broken with TOC 2.0.35 + Pure CSS stopped working

### ISSUE THREAD

**Issue by podrabinek** [ahmedkaludi/Easy-Table-of-Contents#327]
Hello, thank you for the beautiful plugin. Unfortunately, this version has brought some serious issues, so I had to disable the ToC plugin;

- My "Structured plugin" is broken with TOC version 2.0.35, all faq styles are gone (https://wordpress.org/plugins/structured-content/)
- Pure CSS method is not working

I have the the simplest theme, and there are no errors in the DevTools Console.

**Comment by muslimakhan** [comment]
Hey @podrabinek sir,

Please check with latest version 2.0.35.1 and let us know if any issue now faced by your side.

Thanks

**Comment by podrabinek** [comment]
@muslimakhan Hi, "Structured plugin" is fine now, thanks! Pure CSS still doesn't work (no caching plugins, purged Cloudflare cache, tried different settings, no luck)

**Comment by muslimakhan** [comment]
Hey @podrabinek sir, 

Thanks for your feedback!!!

1. can you share your wp-admin credential of live site or you can create stage server and send us details on support page:
https://tocwp.com/contact/

2. can you share with us some screenshots and links for checking?

3. what would be problem faced by Pure CSS option of Easy TOC, am I on same way, are you asking for this settings of our Easy TOC plugin:
https://prnt.sc/KhErB3aKvg_g
or anything else?

Thanks

**Comment by muslimakhan** [comment]
Hey @podrabinek sir, 
Sorry for the inconvenience,

Can you check once your site from this latest zip file:
https://drive.google.com/file/d/1QiNWyG7odkkR9JV453wt5cL4b8SV3PMy/view?usp=sharing

Steps:

Download zip file
https://prnt.sc/UR4FgwVPszdS

Deactivate & Delete current Easy Table of Contents Plugin from plugin page of your admin panel from your website
https://prnt.sc/1FfZT7rIy_3L
https://prnt.sc/A9lmJsOubNT6

Click on Add New Plugin
https://prnt.sc/pAp6yZvkws7G

Click on Upload Plugin:
https://prnt.sc/hSBxRKqfqk8E

Add new downloaded zip file in it & install plugin
https://prnt.sc/BQoRIUzmktyE

Check now your frontend posts & pages where toc is added, and do once clear cache or ctrl + F5 & ctrl + shift + R.

Let us know about your feedback once please, sorry for delay.

Thanks
