### ISSUE TITLE
Apostrophes removed from content

### ISSUE THREAD

**Issue by KippisKippis** [ahmedkaludi/Easy-Table-of-Contents#328]
Latest version (2.0.35 10/29/2022) removes apostrophes from content. For example:

* “we’ll” becomes “well”
* “Economy’s” becomes “Economys”

Found on my site (www.theprogresseconomy.com) after disabling all plugins and turning on individually to see what caused this. It’s only when easy table of contents is enabled that the content is stripped of apostrophes.

**Comment by fsvm88** [comment]
Can confirm: my wife updated the plugin this morning, and shortly afterwards noticed the apostrophes missing.
Disabling the plugin brings the apostrophes back.
It looks like they are filtered server-side: inspecting the content via DevTools does not show them in the HTML.

**Comment by muslimakhan** [comment]
Hey @KippisKippis & @fsvm88 

Please check with latest version 2.0.35.1 and let us know if any issue now faced by your side.

Thanks

**Comment by KippisKippis** [comment]
Works great for me; many thanks for the quick fix
//Adam

**Comment by fsvm88** [comment]
Confirm that it's fixed for me as well 👍 Thanks for the quick turnaround :)

**Comment by muslimakhan** [comment]
Already pushed on Version 2.0.32.1, issue resolved now
