### ISSUE TITLE
Last version removed sidebar & some other contents

### ISSUE THREAD

**Issue by steinba8668** [ahmedkaludi/Easy-Table-of-Contents#329]
After the automatic update of the plugin I have massive visible glitches/problems on my website digitalesleben.blog hosted on WordPress.com)
![9790BFED-153D-4F53-BABD-597D92A38931](https://user-images.githubusercontent.com/107769793/198875251-80f3a8e1-a6cd-4faf-8d89-42b7db9fa9c5.jpeg)
![4EC05B04-CA9C-4174-BEA3-1628E1BF8D73](https://user-images.githubusercontent.com/107769793/198875253-66fa51b8-ed72-48e8-afc9-e77e39524975.jpeg)
![964BAAD6-8510-46EA-9488-C1DE1FEF2314](https://user-images.githubusercontent.com/107769793/198875254-6d0db723-9f24-4d04-a9fa-a11cf7164d86.jpeg)
![889DFA02-1F30-4A8B-8FEB-E61A399EF12F](https://user-images.githubusercontent.com/107769793/198875255-8acf8d3f-3635-428d-a392-53fe51b408d5.jpeg)
![D217BD82-788A-42EE-809C-E181E5D83F0B](https://user-images.githubusercontent.com/107769793/198875256-6c565fff-a9b7-48d1-9954-ea42c6c80edc.jpeg)
![016A2E61-B72B-42CE-8578-0580E04A3B89](https://user-images.githubusercontent.com/107769793/198875258-f8b5232f-a1fc-4e18-b953-caf21524c4e4.jpeg)
![A68990D3-9C7B-4298-A630-5CD904265CE6](https://user-images.githubusercontent.com/107769793/198875261-a9fc696a-cab1-4640-9939-db55ed9c5fcf.jpeg)
. The sidebar is no longer visible on the left side but below the main area. HTML Text is shown below embedded pictures on the side. After deactivation of the Easy TOC plugin everything is working properly.

**Comment by muslimakhan** [comment]
Same: https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/328

**Comment by muslimakhan** [comment]
Hey @steinba8668 

Please check with latest version 2.0.35.1 and let us know if any issue now faced by your side.

Thanks

Thanks

**Comment by steinba8668** [comment]
How can I download 2.0.35.1 to my WordPress.com operated website?Sent from iPhone means full of spell check errorsAm 31.10.2022 um 08:48 schrieb Muslim Ahmad ***@***.***>:﻿
Hey @steinba8668
Please check with latest version 2.0.35.1 and let us know if any issue now faced by your side.
Thanks

**Comment by steinba8668** [comment]
How can I download the version 2.0.35.1 to my WordPress.com operated website?

**Comment by muslimakhan** [comment]
Go to this link:
https://wordpress.org/plugins/easy-table-of-contents

https://prnt.sc/4qbpHNCM3AJ9

and Download latest version

**Comment by steinba8668** [comment]
I installed 2.0.35.1 and the sidebars are back. But visible HTML below picture are still there. Here are some screenshots.Von meinem neuen iPad Pro gesendet 😄Am 31.10.2022 um 09:01 schrieb Muslim Ahmad ***@***.***>:﻿
Go to this link:
https://wordpress.org/plugins/easy-table-of-contents
https://prnt.sc/4qbpHNCM3AJ9
and Download latest version

**Comment by muslimakhan** [comment]
@steinba8668 ,
Please send us screenshots or link so we will check, and I checked this link don't have Easy TOC plugin activated:
https://digitalesleben.blog/2022/10/09/general-magic-und-pocket-crystal-eine-vision-fuer-die-zukunft/

https://prnt.sc/jGxEnqU7GGMD

https://prnt.sc/fVqVkEfIdO0i

Please share your credential of live or stage server on this support link:
https://tocwp.com/contact/

So we will further in deep testing.

Thanks

**Comment by steinba8668** [comment]
I activated Easy TOC now for your tests. Please feel free to check my pages and posts.Von meinem neuen iPad Pro gesendet 😄Am 31.10.2022 um 09:29 schrieb Muslim Ahmad ***@***.***>:﻿
@steinba8668 ,
Please send us screenshots or link so we will check, and I checked this link don't have Easy TOC plugin activated:
https://digitalesleben.blog/2022/10/09/general-magic-und-pocket-crystal-eine-vision-fuer-die-zukunft/
https://prnt.sc/jGxEnqU7GGMD
https://prnt.sc/fVqVkEfIdO0i
Please share your credential of live or stage server on this support link:
https://tocwp.com/contact/
So we will further in deep testing.
Thanks

**Comment by muslimakhan** [comment]
@steinba8668 sir, can you check with this link file of Easy TOC:
https://drive.google.com/file/d/1VP44bopGk_4utDTjIV9VwMogU-JKiWo0/view?usp=share_link

1. download this zip
2. remove activate plugin easy toc
3. and add zip file for installing new files.

and you can share us wp-admin credential for testing, you can create stage server too:
https://tocwp.com/contact/

**Comment by steinba8668** [comment]
Sorry, I don’t feel comfortable with it. I’m not that technically experienced to check the impact of this step you ask from me. I cannot support you more on this. I will keep Easy TOC activated for the next hour but this is all I want to get involved in your bug fixing activities.Sent from iPhone means full of spell check errorsAm 31.10.2022 um 09:46 schrieb Muslim Ahmad ***@***.***>:﻿
@steinba8668 sir, can you check with this link file of Easy TOC:
https://drive.google.com/file/d/1VP44bopGk_4utDTjIV9VwMogU-JKiWo0/view?usp=share_link

download this zip
remove activate plugin easy toc
and add zip file for installing new files.

and you can share us wp-admin credential for testing, you can create stage server too:
https://tocwp.com/contact/

**Comment by muslimakhan** [comment]
@steinba8668 sir,
Easy TOC is working fine now can you clear us do you download zip file from google drive link and attach in your website or its working on same previous version no need to add zip file? 

https://digitalesleben.blog/2022/10/09/general-magic-und-pocket-crystal-eine-vision-fuer-die-zukunft/

https://prnt.sc/lb2hUqnUG686
https://prnt.sc/XW-Yz1uCt979
https://prnt.sc/YbPFhP9yX06_
https://prnt.sc/BflmM73-5zx2

Thanks

**Comment by steinba8668** [comment]
Actually I switched to TOC+ for a quick workaround. What you see on your screenshots is TOC+. Sent from iPhone means full of spell check errorsAm 31.10.2022 um 12:14 schrieb Muslim Ahmad ***@***.***>:﻿
@steinba8668 sir,
Easy TOC is working fine now can you clear us do you download zip file from google drive link and attach in your website or its working on same previous version no need to add zip file?
https://digitalesleben.blog/2022/10/09/general-magic-und-pocket-crystal-eine-vision-fuer-die-zukunft/
https://prnt.sc/lb2hUqnUG686
https://prnt.sc/XW-Yz1uCt979
https://prnt.sc/YbPFhP9yX06_
https://prnt.sc/BflmM73-5zx2
Thanks
