### ISSUE TITLE
Numbers are wrong

### ISSUE THREAD

**Issue by livemoretravelmore** [ahmedkaludi/Easy-Table-of-Contents#330]
Table of contents showing number 1 for all options in the summary
<img width="732" alt="Screen Shot 2022-11-03 at 11 06 24" src="https://user-images.githubusercontent.com/43389487/199742324-f2b3f79a-c722-4da4-96f0-fbbc207903ec.png">

**Comment by livemoretravelmore** [comment]
example [](https://www.livemoretravelmore.com/best-winter-vacations-us/)

**Comment by livemoretravelmore** [comment]
https://www.livemoretravelmore.com/best-winter-vacations-us/

**Comment by muslimakhan** [comment]
Hey @livemoretravelmore ,

Your theme CSS have some conflict with our Easy TOC Plugin CSS, please check video once:

https://user-images.githubusercontent.com/12198305/200106546-9d2e61a8-9341-401f-8719-aebf407b3481.mp4

It will be resolved on next future milestone

**Comment by muslimakhan** [comment]
Hey @livemoretravelmore , 

we have resolved the issue and checked from our end can you check once from your site from this zip file link:

https://drive.google.com/file/d/1Km1GU-BnXIHkN1Yv3pZCFCNSptNQ-KXj/view?usp=sharing

Thanks

**Comment by muslimakhan** [comment]
We are going to reopen this ticket due to create issue for another users, need to fix again.

Reference Links:
https://wordpress.org/support/topic/ez-toc-settingsexclude_css-not-working/
https://wordpress.org/support/topic/v2-0-37-does-not-honor-prevent-the-loading-the-core-css-styles-option/

**Comment by Sdaud1950** [comment]
same issue  https://magazine3.in/conversation/74866?folder_id=29

**Comment by muslimakhan** [comment]
Hi All,

Now, we have resolved this issue, please check from this link and let us know now resolved or not?
https://github.com/ahmedkaludi/Easy-Table-of-Contents/archive/refs/heads/2.0.40.zip

Thanks
@muslimakhan 
Magazine3 Developer
