### ISSUE TITLE
When headings are made in  quotes marks, they do not scroll to the article.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#343]
While using the **Mediavine Trellis theme** When headings are made in quotes marks, they do not scroll to the article.

Ref video: https://monosnap.com/direct/XzV8nrQPHW9EaLTrX4lqMm7J70CnZb

Ref ticket:https://magazine3.in/conversation/69416?folder_id=29

**Comment by ankit644** [comment]
Another user facing the same issue.

Ref ticket: https://magazine3.in/conversation/71255?folder_id=11

**Comment by sean-dunwoody** [comment]
I've been investigating this for a client, and have tracked down the cause to this file:

web/content/plugins/easy-table-of-contents/includes/inc.cord-functions.php 

line 310:

```
$needle = str_replace(array('’','“','”'), array('\'','"','"'), $needle);
```

This modifies the needle, and replaces [smart quotes](https://editorsmanual.com/articles/smart-vs-straight-quotes/) with straight quotes.

So, e.g. this:

`Lorem ipsum they’re`

Becomes this:

`Lorem ipsum they're`

These 2 strings are now no longer identical, so they don't match. This causes the code to exit out, and means that this heading in the content will not output the relevant anchor ID to match with the sidebar links.

This line of code has no comment explaining why it has been implemented, and the commit message doesn't really offer any clues either:

https://github.com/ahmedkaludi/easy-table-of-contents/commit/6a1783f906b706a51b14b98ebfdb6c9a8107b828

The message was:

> Updated the master as per wp.org

I've had a look at the repo on wp.org and I can't see any relevant commit messages there either:

https://plugins.trac.wordpress.org/log/easy-table-of-contents/trunk/includes/inc.cord-functions.php

My best guess is that this was implemented as part of the broader if statement it exists within. It looks like it is a fallback that attempts to deal with unusual encoding leading to a failure to find the relevant heading.

But I'm not sure if it would have ever worked as intended? If the original string contained smart quotes, then why replace them? PHP can deal with smart quotes using the `mb_strpos` so it shouldn't be a problem.

Removing this line of code fixes the problem. I'd be happy to open a PR that does this unless anyone is aware of a good reason why this line of code exists?

If not, then an alternative might be to only implement the replace if `$start` is again equal to `false` - the `mb_strpos` method could then be run one final time afterwards.
