### ISSUE TITLE
Broken CSS after the new update

### ISSUE THREAD

**Issue by CyberWaters** [ahmedkaludi/Easy-Table-of-Contents#352]
We use a custom-developed theme and ToC. After the last update (not the Wordpres Compatibility, the previous one) ToC has broken the layout. We did not change the settings. For everything to work we used a parameter: 
"Prevent the loading the core CSS styles. When selected, the appearance options from above will be ignored."

now it looks like this. Does the parameter still work? Have there been any class name changes? JS changes?

Please point me to the older version of ToC.

<img width="323" alt="Screenshot 2022-12-01 at 14 45 55" src="https://user-images.githubusercontent.com/104513644/205082505-042a1944-ea29-4851-8bb7-7faea9183513.png">

**Comment by muslimakhan** [comment]
Same #330

**Comment by muslimakhan** [comment]
Hi @CyberWaters,

Now, we have resolved this issue, please check from this link and let us know now resolved or not?
https://github.com/ahmedkaludi/Easy-Table-of-Contents/archive/refs/heads/2.0.40.zip

Thanks
@muslimakhan 
Magazine3 Developer
