### ISSUE TITLE
ETOC stops working (again) after plugin update

### ISSUE THREAD

**Issue by MS-AU** [ahmedkaludi/Easy-Table-of-Contents#353]
This is a great free plugin. Thanks for making it!

When we started using the Easy TOC plugin approx 3-4 months ago it appeared to worked 100%. However, most updates after 2.0.34 'break' the plugin such that it no longer displays the links

Here's an example on one of our sites where your Easy TOC plugin is NOT working - version 2.0.39:
https://www.msiaustralia.org.au/accessible/clinical-services-sedation-information/

Here's an example on the same site (in beta) where your Easy TOC plugin IS working - version 2.0.34:
https://beta.msiaustralia.org.au/accessible/clinical-services-sedation-information/

**Comment by muslimakhan** [comment]
Hi @MS-AU ,

Please send us your feedback on last email.

Thanks & Regards
@muslimakhan
Magazine3 Developer

**Comment by Sanjeevsetu** [comment]
Hi @MS-AU,

If you still facing the issue please create new thread and contact us. Due to inactiveness on this ticket, I am closing it
