### ISSUE TITLE
Option to hide Easy Toc from posts of a specific category.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#354]
Reference ticket: https://wordpress.org/support/topic/exclude-easy-toc-from-posts-by-category-wordpress/

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/99661?folder_id=21

**Comment by Sasirekhamarella** [comment]
Another user: https://wordpress.org/support/topic/exclude-url-9/

**Comment by Sanjeevsetu** [comment]
Duplicate of https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/631
