### ISSUE TITLE
Shortcode is not working with Advanced Custom Fields PRO

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#358]
Ref ticket:- https://magazine3.in/conversation/78314?folder_id=21

Description:-
User adds the TOC shortcode in ACF Flexible Blocks, but it's not reflecting in the front end.

Issue screenshot:-
https://prnt.sc/0DGMu2KrhG7A

**Comment by Sanjeevsetu** [comment]
It has been fixed in new added feature ACF support
