### ISSUE TITLE
Need to create an option where users can show or hide the TOC on mobile devices and desktops.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#362]
Need to create an option where users can show or hide the TOC on mobile devices and desktops.

Ref ticket: https://magazine3.in/conversation/81011?folder_id=29

**Comment by Sdaud1950** [comment]
This user also wants the same option: https://magazine3.in/conversation/127354?folder_id=29

**Comment by Sanjeevsetu** [comment]
Reference ticket -: https://magazine3.in/conversation/92401?folder_id=23

**Comment by Sanjeevsetu** [comment]
Another user is requesting the same functionality:
https://wordpress.org/support/topic/option-to-select-sticky-toc-for-mobile-or-desktop/

**Comment by Sanjeevsetu** [comment]
Another user : https://wordpress.org/support/topic/option-to-select-sticky-toc-for-mobile-or-desktop/#post-17105006

**Comment by Sanjeevsetu** [comment]
When enabling Sticky TOC, it does show on desktop/mobile/tablet. There is a need to add an option to show it only on mobile.

Reference user -: https://wordpress.org/support/topic/hide-sticky-for-desktop-and-counter-for-sticky/
