### ISSUE TITLE
Licences Key is not activating. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#364]
When we are trying to activate the licence key, it is showing "activating," but never "activate."

 Ref Screenshhot: https://prnt.sc/Vs5pESWAGoCM 

Ref Ticket: https://magazine3.in/conversation/80595?folder_id=29

**Comment by muslimakhan** [comment]
I have checked by code and console ajax request, this is from api calling, api calling url is `define( 'EASYTOC_PRO_DATA_STORE_URL', 'https://tocwp.com/' );` , and api return error is `item_name_mismatch`:
https://prnt.sc/9QeACLWRhjbt

```php
 define( 'EASYTOC_PRO_DATA_ITEM_NAME', 'Easy table of contents pro' );
 ```
 this is item name which are added in our pro files.
 Please check from webmaster or management team.
