### ISSUE TITLE
Need to create a new functionality where the user can expend the TOC. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#365]
There is a need to develop a new feature that allows the user to expand the TOC.

Please check this reference screenshot: https://prnt.sc/aCHR6EGSvOdM When we click on the three dots, the TOC expands below. 

Ref ticket. https://magazine3.in/conversation/82220?folder_id=29

**Comment by Sanjeevsetu** [comment]
This is a duplicate ticket of https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/474 and has been pushed in v2.0.57.
