### ISSUE TITLE
Title paragraph <p> tag dynamically changed into other tags 

### ISSUE THREAD

**Issue by muslimakhan** [ahmedkaludi/Easy-Table-of-Contents#367]
### Description
Need to change TOC title paragraph `<p>` tag into `<h2>` tag or other tags dynamically through admin settings.

#### Reference Screenshot
![photo_2022-12-19_19-25-28](https://user-images.githubusercontent.com/12198305/208588707-9761bc53-5bb2-4e95-b93d-fa5aa6b51f03.jpg)

**Comment by Sanjeevsetu** [comment]
This feature has been added in our latest version. Try v2.0.60 and above.
