### ISSUE TITLE
Heading not working in the Russian language on the Pale Moon Browser.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#368]
Bug Name: Heading not working in the Russian language on the pale Moon Browser.
Area: post/pages
Plugin Version: 2.0.40
Pale Moon browser version: 31.4.1
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/81925?folder_id=27
Reference video: https://drive.google.com/file/d/1uXmoLQVQM3w3wJSQj4DO1eZkmOxsv63a/view?usp=sharing

Description: Russian headings are now working/unclickable on the Pale Moon Browser.

Steps to Reproduce:

Login into your wp-admin dashboard
Activate the plugins Easy Table Of Contents
Create a new post with Russian language content
Open the post on Pale Moon Browser.

Output:
TOC heading will not work/jump to the content.

**Comment by muslimakhan** [comment]
Forum Tickets: 
https://wordpress.org/support/topic/update-to-2-0-44-caused-dashboard-critical-error/
https://wordpress.org/support/topic/critical-error-after-update-27/

Fixed Now.

**Comment by muslimakhan** [comment]
Description: Issue, key_exists() expects parameter 2 to be array, bool given in [...]/wp-content/plugins/easy-table-of-contents/includes/inc.functions.php on line 200

Referent tickets:
https://magazine3.in/conversation/96536?folder_id=29
https://wordpress.org/support/topic/warning-and-fatal-error-with-version-2-0-44-1-and-php-8-1/
