### ISSUE TITLE
Conflict issue with latest version in Generatepress Theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#370]
Ref ticket:- https://magazine3.in/conversation/81617?folder_id=21

Description:-
Scroll back to top is not working with the latest version of TOC.

Issue video:-
https://monosnap.com/direct/aXziGwwxVz8054BLbyM6NTXaOO8yaB

**Comment by muslimakhan** [comment]
Same: #143
