### ISSUE TITLE
Need to add "Change Header Label" option for specific post/page.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#371]
There is a need to add "Change Header Label" option for specific post/page so that users can put different Header for different posts.

Reference ticket -: https://magazine3.in/conversation/83225?folder_id=23

**Comment by Sanjeevsetu** [comment]
This is duplicate of https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/472
