### ISSUE TITLE
When a user adds the TOC while using Elementor PRO, the TOC does not scroll down.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#372]
When we have more than 20 headings on the TOC and use Elementor PRO to add the TOC shortcode to the sidebar, it works fine until 19 links, but then the TOC does not scroll down..

Ref Ticket .https://magazine3.in/conversation/80595?folder_id=29

**Comment by Sanjeevsetu** [comment]
Plz discuss this with me before working on it.
