### ISSUE TITLE
Easy Table Of contents not appearing properly on AMP version.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#373]
Bug Name: Easy Table Of contents not appearing properly on the AMP version.
Area: AMP post/pages
Version Number: 1.0.77.54.1
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/81315?folder_id=27

Reference screenshot: https://prnt.sc/uWSSJjJUKbfd

Steps to Reproduce:

Login into your wp-admin dashboard
Activate the plugin AMPforWP and Easy Table Of Contents.
Visit a post that has TOC enabled on it in the AMP version.

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/amp-problem-11/#post-16301888

**Comment by Sdaud1950** [comment]
Same issue.
https://magazine3.in/conversation/82644?folder_id=29

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/108480?folder_id=21

**Comment by Sanjeevsetu** [comment]
There is a pro extension for ampforwp. Please try that. Ref: https://ampforwp.com/addons/easy-table-of-contents-for-amp/
