### ISSUE TITLE
Empty space appears after removing the header label.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#376]
Ref ticket:-https://magazine3.in/conversation/81617?folder_id=21

Description:-
The user removes the Header Label but an empty space appears in TOC.

Issue screenshot:-
https://monosnap.com/direct/PKqYPslxWeKV4ytmuA3KQReqsSJOZj
https://monosnap.com/direct/h1VyZ0YtVCFRZWXcfFyqhtGFRTG85x

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/space-impossible-to-remove-at-the-top/

**Comment by aitorserra** [comment]
I think I also have the same problem: https://www.honesting.es/posicionamiento-web/

I tried to disable the caché plugins but it keeps failing. Have you found the bug for the failure? Thank you.

**Comment by aitorserra** [comment]
Is there a deadline for when it could be fixed or a temporary solution? Thank you

**Comment by sajandara** [comment]
A user with the same issue:
https://magazine3.in/conversation/94425?folder_id=27

**Comment by muslimakhan** [comment]
Hey All of you,

This issue is working on, we will update in next EzTOC version 2.0.45

Thanks
