### ISSUE TITLE
Need to fix TOC auto add on product categories

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#377]
When we are using TOC with woo-commerce and enable TOC support for only posts/pages, it also auto-added to product category pages which generates the error.

Reference ticket: https://magazine3.in/conversation/72604?folder_id=23

**Comment by GrischaK** [comment]
We have also this problem

**Comment by Sanjeevsetu** [comment]
Hi @GrischaK 

Could you help me if the issue still persist at your end because in recent updates we have fixed similar kind of issue.

**Comment by muslimakhan** [comment]
Hi @GrischaK ,
I have checked your issue on our dev environment, but not found your issue on our end, so please provide us stage server wp admin credentials with stage server ftp credential details on this support link:
https://tocwp.com/contact/

Thanks

**Comment by Sanjeevsetu** [comment]
This is related to https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/134. I am closing it
