### ISSUE TITLE
ez-toc shortcode not working to hide the initial view on a page/post

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#378]
Scenario: [ez-toc initial_view=hide] -- the shortcode not working. 
Reference ticket: https://wordpress.org/support/topic/show-expanded-toc-by-default-but-show-collapsed-on-specific-pages/

**Comment by Sdaud1950** [comment]
Another user with the same issue.
https://magazine3.in/conversation/93660?folder_id=29

**Comment by Sanjeevsetu** [comment]
This fix caused other issue with toggle. such as we have to click two time to toggle initially
