### ISSUE TITLE
Conflict issue with Argu theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#384]
Ref:- https://magazine3.in/conversation/86712?folder_id=21

Description:-
When the user clicks on the title it scrolls up.

Issue video URL:
https://monosnap.com/direct/uLtMvdgiXL8Vgchq1UQdUPGArpaINv

**Comment by Sanjeevsetu** [comment]
This issue is due to Argu theme argu-main.js. They have used scroll top on every anchor links click inside page. We do not know why. So this is not bug from ETOC. Please contact theme author. I am closing it
