### ISSUE TITLE
Links not working in the Japanese language.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#387]
Bug Name: Links not working in the Japanese language.
Area: Frontend
Version Number: 2.0.41
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/87525?folder_id=27

Description: If the website is in the Japanese language the TOC links will not work/jump to the content

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/87956?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/87798?folder_id=21

**Comment by 77naveenop** [comment]
Also not working in Russian.

Ref. ticket -:https://magazine3.in/conversation/83321?folder_id=23

**Comment by muslimakhan** [comment]
Already did in milestone 2.0.41
