### ISSUE TITLE
If the heading contains numbers then links stop working.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#388]
Bug Name: If the heading contains numbers then links stop working.
Area: Network section
Version Number: 2.0.41
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/87890?folder_id=27

Description: If the user has added a number to their heading then that heading will not work/jump to the content.

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/error-with-the-links-no-create-the-anchor-in-the-headings/

**Comment by Sanjeevsetu** [comment]
This issue has been solved in previous update and user has confirmed the same. I am closing it
