### ISSUE TITLE
Anchor links are no longer appearing in the URLs

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#394]
Bug Name: Anchor links are no longer appearing in the URLs
Area: post/pages
Version Number: 2.0.42 01
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/89998?folder_id=4

**Comment by muslimakhan** [comment]
User can't go back through back button of browser it is going to toc section.

Reference Ticket: https://magazine3.in/conversation/88784?folder_id=3
