### ISSUE TITLE
While using the TOC on the mobile devices the user is geeting blank screens ("User specific")

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#397]
When the user is adding the TOC, it works fine on the desktop, but on mobile devices, it shows a blank page when the TOC is enabled.

Ref screenshot of the mobile version: https://prnt.sc/-ajSwDTKWDh0 

Ref ticket:https://magazine3.in/conversation/86437?folder_id=29

**Comment by elizatlawy** [comment]
This issue happens on my blog: https://backpackers.co.il/ so I will add that this reproduces only with Android devices ad works fine on iOS devices.

**Comment by Sanjeevsetu** [comment]
Waiting for user replt

**Comment by Sanjeevsetu** [comment]
Again still waiting for user.

**Comment by Sanjeevsetu** [comment]
This is not being generated at our end and user is not co-operating so I am closing it. Please create new tickets if again issue comes
