### ISSUE TITLE
Need to add new hooks for sidebar sticky toc widget in documentation

### ISSUE THREAD

**Issue by muslimakhan** [ahmedkaludi/Easy-Table-of-Contents#398]
## Description:
Recently a new widget added `Sidebar Sticky TOC` and new hooks also added for this widget. So we need to add these hooks in our documentation page:

### Reference Screenshots:

https://prnt.sc/o6DGV8j1dPam

https://prnt.sc/RQ9hBdxm24GD

**Comment by Sanjeevsetu** [comment]
This is docs related ticket. We have trello for these kind of tickets.
