### ISSUE TITLE
Issue with last update

### ISSUE THREAD

**Issue by omarcarrillo76** [ahmedkaludi/Easy-Table-of-Contents#401]
Hi, i have an issue with the last update. my page doesnt load as you can see in the attached screen, i noticed that is TOC plugin when i started to deactive one by one the plugins on my site. can anyone help? 

[https://drive.google.com/file/d/1ZKfqxGOUCRrTk057kUZ0PuW2VCUuSx4r/view?usp=share_link](url)

**Comment by muslimakhan** [comment]
Hey @omarcarrillo76 ,

Please check with latest version 2.0.44.3 and let us know your feedback.

Thanks

**Comment by muslimakhan** [comment]
I have just checked your site:
https://prnt.sc/rOiI2mzhVxGZ

Easy TOC Version 2.0.44.2 is live and working well.

is this working as you like?

**Comment by Sanjeevsetu** [comment]
Hi @omarcarrillo76 

Do you still have that issue? If it is than we have to debug the issue, you just contact us via http://tocwp.com/contact.

**Comment by omarcarrillo76** [comment]
i resolved by do it again
