### ISSUE TITLE
Links are not working if the plugin Elementor pro is activated

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#403]
Bug Name: Links are not working if the plugin Elementor pro is activated
Area: Frontend
Version Number:  2.0.43
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/88960?folder_id=27
Description: If the plugin Elementor is activated, the links of Table Of Content stop working.

**Comment by Sanjeevsetu** [comment]
Waiting for user reply.

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply. I am closing the ticket for now. If issue is still there and user reply on it. We will reopen it
