### ISSUE TITLE
The Toc link does not jump to the content.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#405]
When TOC headings are added through the Otter block, the TOC links do not jump to the content. When the Smooth Scroll option is disabled, the links work fine.
Ref video: https://monosnap.com/direct/8eNU7SkTD6eM7Y1uOrpMxXjQQ1TUfH

Ref ticket: https://magazine3.in/conversation/88784?folder_id=29

**Comment by muslimakhan** [comment]
Same #394 and already resolved.
