### ISSUE TITLE
Add a new feature to customize the highlighting color of the headings.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#411]
Need to create a new feature where the user can customize the highlighting color of the headings.

Ref Ticket: https://magazine3.in/conversation/95064?folder_id=29

**Comment by Sanjeevsetu** [comment]
More Ref: Ref : https://prnt.sc/kJIScLoRuPuq

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/455
