### ISSUE TITLE
Easy TOC is showing the wrong TOC on each post

### ISSUE THREAD

**Issue by apashanota** [ahmedkaludi/Easy-Table-of-Contents#416]
Hi. We had to deactivate the plugin because it's showing the wrong table of content on each page. What could be causing this issue? I already cleared the caches and checked a few of the more obvious potential plugin conflicts. Have you seen this before? Thanks for your help!
![FireShot Capture 007 - TRAVELING WITH YOUR DOG IN 10 U S  CITIES  - Travels with Talek_ - travelswithtalek com](https://user-images.githubusercontent.com/124106323/215914564-4ae70068-8ed1-42ca-a668-73251c7fb1af.jpg)

**Comment by Sanjeevsetu** [comment]
Hi @apashanota 

Could you activate the plugin again and share the website url so that we can look into it or if you can contact us via https://tocwp.com/contact/.

**Comment by Sdaud1950** [comment]
This user is experiencing the same problem:  https://magazine3.in/conversation/100584?folder_id=29

**Comment by ankit644** [comment]
https://magazine3.in/conversation/100596?folder_id=11 also this user experiencing the same issue.

**Comment by sajandara** [comment]
A user is facing the same issue.
https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/416

**Comment by sajandara** [comment]
A user is facing the same issue.
https://magazine3.in/conversation/100542?folder_id=27

**Comment by Sdaud1950** [comment]
This user is experiencing the same problem https://magazine3.in/conversation/100613?folder_id=29

**Comment by Sanjeevsetu** [comment]
Hi @apashanota 

We have already fixed this issue and have released on wp.org. Did you try with v2.0.45.1. If not than please try and let us know.
