### ISSUE TITLE
The sticky side bar is not working properly.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#418]
When we use Stack Theme and set the sticky sidebar, it's not working.

Ref video:https://monosnap.com/direct/wE7jFr927pvqJZ3hANmaCBbSPAdDkb

Ref ticket:https://magazine3.in/conversation/98694?folder_id=29

**Comment by muslimakhan** [comment]
https://prnt.sc/4Xj4JIw8mZsg

**Comment by muslimakhan** [comment]
https://prnt.sc/8r6IaeApIUjF
