### ISSUE TITLE
The attribute 'area-label' may not appear in tag 'a'

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#424]
Ref ticket:- https://magazine3.in/conversation/104418?folder_id=21

Description:-
a href=# class="ez-toc-pull-right ez-toc-btn ez-toc-btn-xs ez-toc-btn-default ez-toc-toggle" area-label=ez-toc-toggle-icon-1> code is added to AMP and creates an error.

**Comment by Sasirekhamarella** [comment]
Same issue:https://wordpress.org/support/topic/amp-validation-error-area-label-not-suitable-for-tag-a/

**Comment by isrgrajan** [comment]
Fixed and made pull request in #425

**Comment by Glifaus** [comment]
Hi, came for the same error. I made miself the fix, hope new versions have amp test aswell.
I expect new version soon. Thanks for the quick fix!

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/106415?folder_id=21

**Comment by 77naveenop** [comment]
Another user -: https://magazine3.in/conversation/104992?folder_id=23

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/109668?folder_id=21

**Comment by sajandara** [comment]
Some users are facing the same issue
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5406

**Comment by Sanjeevsetu** [comment]
It has been fixed in version 2.0.45.1
