### ISSUE TITLE
Need to add option to show on Tags/Categories

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#427]
Currently, we can add TOC in the category page via shortcode but in some use cases, it shows the wrong TOC heading that comes from posts whereas it should show the heading of the page.

Reference ticket -: https://magazine3.in/conversation/101468?folder_id=23

**Comment by Sanjeevsetu** [comment]
We missed an option in admin panel so I am opening the ticket
