### ISSUE TITLE
Easy Table Of contents not appearing properly on official AMP 

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#428]
Ref ticket:- https://magazine3.in/conversation/108480?folder_id=4

Description:-
Toggle not working properly.

Issue screenshot:-
https://prnt.sc/ChYgTGPTkjPq

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/119280?folder_id=21

**Comment by Sanjeevsetu** [comment]
This issue seems not valid. We have separate pro extension for table of content in AMPforWP. Please recommend to users.

Link : https://ampforwp.com/addons/easy-table-of-contents-for-amp/
