### ISSUE TITLE
Custom option to set header label on each post/page

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#429]
Scenario: The user wants to set the title on each post/page individually.
https://prnt.sc/-FLnN_lxzxj8

Reference ticket: https://wordpress.org/support/topic/custom-title-on-each-post/

**Comment by Sanjeevsetu** [comment]
It is a duplicate ticket of https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/472. I am closing it
