### ISSUE TITLE
There is an error in the TOC when a user test his or her site using the https://wave.webaim.org/ tool. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#430]
When a user tests his or her site using the https://wave.webaim.org/ tool, there is an issue with the TOC in the tool report.

error is: "Empty form label" and "Multiple form labels."

Ref Ticket; https://magazine3.in/conversation/110708?folder_id=29

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply
