### ISSUE TITLE
Add a new Placement option to Sticky Toggle Option.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#442]
Add a new Placement option to the Sticky Toggle Option which will help the user to place the Sticky Toggle on the **Right** side of the page/post.

Ref ticket: https://magazine3.in/conversation/118310?folder_id=27

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/question-of-index/
