### ISSUE TITLE
Gutenberg editor freezes when we use shortcode by using reusable blocks

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#443]
Scenario: Getting a blank screen and a lot of time is taking if we try to open the post and it's not even updating the post if we try to update the post after adding the shortcode using reusable block by using Gutenberg editor.

Reference screenshot:https://prnt.sc/WKlQPTQ5xUDv
Reference ticket: https://wordpress.org/support/topic/post-not-opening-and-gutenberg-editor-freezes-when-i-use-reusable-shortcode-toc/

**Comment by Sanjeevsetu** [comment]
This solution creates new issue https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/470. so We are reopening it and will find better solutions
