### ISSUE TITLE
TOC is not working correctly

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#444]
When we are adding TOC via auto insert, it is not working correctly. User has WP Bakery Pagebuilder unicode theme.

Reference ticket -: https://magazine3.in/conversation/108428?folder_id=23

**Comment by Sanjeevsetu** [comment]
Waiting for user reply.

**Comment by Sanjeevsetu** [comment]
We are unable to re create the issue at our end and user is not replying on queries so I am closing this ticket.
