### ISSUE TITLE
unable to crawl data if the content is added via different modules

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#448]
unable to crawl data if the content is added via different modules

Ref ticket: https://magazine3.in/conversation/120647?folder_id=27

**Comment by muslimakhan** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/2eb163726d78040f613f2a25a1ea5a02247879cf

**Comment by muslimakhan** [comment]
Revision 1st guidance by @Sanjeevsetu sir
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/58d624fbb323cc28252bf36dac8dee90ce448eed

**Comment by muslimakhan** [comment]
Revert Code on PRO:
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/1140b21b95d552a8dc2705f37e9eb935bd5d7f1b

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/6e1630c755f823da429ef3d2f5be51e2e62fae43

https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/763b061e0d7dd200e66de2ee3bbe837a0abc0e1a

**Comment by akshaywali** [comment]
pushed in ETOC 2.0.48 & ETOC PRO 1.0.8
