### ISSUE TITLE
While using the contact form with the Avada child theme, when TOC is enabled, the contact form shows twice.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#449]
While using the contact form with the Avada child theme, when TOC is enabled, the contact form show Twice

Ref video: https://monosnap.com/direct/GSwXuhM869qhgUONWU89ZYiG9l4kts 

Ref Ticket: https://magazine3.in/conversation/124254?folder_id=29

**Comment by Sanjeevsetu** [comment]
This is not right solution. We have to find better one so moving it on next milestone.

**Comment by muslimakhan** [comment]
The modifications are following,
1. Add the code below to exclude the form heading from the toc.
```php
/**
 * Remove the CAR FORM shortcode content headings.
 *
 * @since 2.0.48
 */
add_filter(
  'ez_toc_exclude_by_selector',
  function( $selectors ) {

    $selectors['avada-child-car-form1'] = '.car-form';

    return $selectors;
  }
);

/**
 * Remove the CAR FORM shortcode content headings.
 * for exclude headings
 * @since 2.0.48
 * 
*/
add_filter(
  'ez_toc_exclude_headings',
  function( $exclude ) {

    $excludeHeadings = "Wheels & Tires|Key & Battery|Starts & Drives|Mirrors, Glass, & Lights|Flood & Fire Damage|Alright! Let*";
    if( $exclude !== null && !empty( $exclude ) ) {
      $exclude .= $excludeHeadings;
    } else {
      $exclude = $excludeHeadings;
    }

    return $exclude;
  }
);
```

2. Add the class |class='car-form'| in a parent div.
line 1981 
```html
class='car-form'
```

3. You have added echo which replaced with return $output; 
|line 5805 echo $output => return $output;|
```php
return $output
```

Plugin and code zip file.
https://drive.google.com/drive/folders/1KVLKAmNpPlaX4x13cbVDXzXZSlfaUYAO?usp=sharing

Sent to user created draft by @sajandara
