### ISSUE TITLE
Tap targets are not sized appropriately 85% appropriately sized tap targets 

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#450]
Ref ticket:-https://magazine3.in/conversation/123692?folder_id=21

Description:-
Warning appears in pagespeed Insights SEO section

Issue screenshot:
https://prnt.sc/gtto4moKxmGe

**Comment by muslimakhan** [comment]
User End issue is resolved but Google Page Speed showing some 74% issue in gap of easy toc container anchor headings in other places like test server with different different theme so need to be more debug on it.

**Comment by muslimakhan** [comment]
Admin Options -> Headings Padding:
https://prnt.sc/zt35mY00Qx3h
https://prnt.sc/cko8ttZ3vemn

**Comment by muslimakhan** [comment]
Admin Options Layout Changed:
https://prnt.sc/Tc7lLMuyxlhV
