### ISSUE TITLE
Toc is not running when custom headings added in Ad Insertor Pro plugin

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/Easy-Table-of-Contents#458]
Ref ticket:- https://magazine3.in/conversation/126625?folder_id=11

**Comment by muslimakhan** [comment]
Exclude Heading `Featured Videos` Resolve the Issue: 
https://prnt.sc/2RFXzTjlEQGy

**Comment by Sanjeevsetu** [comment]
There was some settings issue at user end. It has been solved at user end
