### ISSUE TITLE
Need to add a option to show only sticky toggle TOC

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#460]
Actually, when anyone setup auto-insert and sticky toggle to together then only sticky Toggle TOC shown on the site otherwise if we disable the auto-insert to remove normal TOC to show only Sticky Toggle then TOc got disappear.

Reference Ticket  -: https://magazine3.in/conversation/127687?folder_id=23

**Comment by Sanjeevsetu** [comment]
It has been solved from v2.0.56. We have now separate enable support option for sticky toggle/toc
