### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/Easy-Table-of-Contents#461]
Fatal error: Uncaught Error: Class "ezTOC_Option" not found in D:\XAMPP\htdocs\magazine3\wp-content\plugins\easy-table-of-contents-pro\easy-table-of-contents-pro.php:186 Stack trace: #0 D:\XAMPP\htdocs\magazine3\wp-includes\class-wp-hook.php(308): ez_toc_pro_sticky('') #1 D:\XAMPP\htdocs\magazine3\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 D:\XAMPP\htdocs\magazine3\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #3 D:\XAMPP\htdocs\magazine3\wp-includes\general-template.php(3049): do_action('wp_head') #4 D:\XAMPP\htdocs\magazine3\wp-content\themes\Avada\header.php(21): wp_head() #5 D:\XAMPP\htdocs\magazine3\wp-includes\template.php(783): require_once('D:\\XAMPP\\htdocs...') #6 D:\XAMPP\htdocs\magazine3\wp-includes\template.php(718): load_template('D:\\XAMPP\\htdocs...', true, Array) #7 D:\XAMPP\htdocs\magazine3\wp-includes\general-template.php(48): locate_template(Array, true, true, Array) #8 D:\XAMPP\htdocs\magazine3\wp-content\themes\Avada\single.php(15): get_header() #9 D:\XAMPP\htdocs\magazine3\wp-includes\template-loader.php(106): include('D:\\XAMPP\\htdocs...') #10 D:\XAMPP\htdocs\magazine3\wp-blog-header.php(19): require_once('D:\\XAMPP\\htdocs...') #11 D:\XAMPP\htdocs\magazine3\index.php(17): require('D:\\XAMPP\\htdocs...') #12 {main} thrown in D:\XAMPP\htdocs\magazine3\wp-content\plugins\easy-table-of-contents-pro\easy-table-of-contents-pro.php on line 186
There has been a critical error on this website.

**Comment by muslimakhan** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/692bb88082e1958de929e46bb65a1a1350cdf74a
