### ISSUE TITLE
Warning: Attempt to read property "id" on null

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/Easy-Table-of-Contents#463]
Warning: Attempt to read property "id" on null in D:\XAMPP\htdocs\magazine3\wp-content\plugins\Easy-Table-of-Contents\easy-table-of-contents.php on line 1142

**Comment by Sdaud1950** [comment]
same issue 

https://magazine3.in/conversation/129255?folder_id=29
https://magazine3.in/conversation/129201?folder_id=29
https://magazine3.in/conversation/129087?folder_id=29

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/129127?folder_id=21
