### ISSUE TITLE
Add a new feature change a header label for specific post or page.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#472]
Ref ticket:- https://magazine3.in/conversation/132868?folder_id=21

Description:-
User want to change the header label in specific post and pages.

**Comment by Sdaud1950** [comment]
Same feature for this user as well.: https://magazine3.in/conversation/171234?folder_id=29

**Comment by Sanjeevsetu** [comment]
Reference ticket -: https://magazine3.in/conversation/83225?folder_id=23
