### ISSUE TITLE
Need to add new feature, user should be able to show only the amount of headings they want and rest should be as "ViewMore"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#474]
The user should be able to show only the amount of heading they want and the rest of the headings should be shown after the visitor clicks on "View More"

Ref ticket: https://magazine3.in/conversation/133794?folder_id=27

**Comment by sajandara** [comment]
Another user needs this functionality: https://magazine3.in/conversation/194388?folder_id=27

**Comment by askcode21** [comment]
another user requested this feature: https://wordpress.org/support/topic/show-only-the-first-4-subheadings/#post-17109790
