### ISSUE TITLE
Table of Contents shows up but does not work as expected with shortcode

### ISSUE THREAD

**Issue by Linhin** [ahmedkaludi/Easy-Table-of-Contents#48]
Thank you for great Table of Contents for Wordpress. I'm just using Easy Table of Contents. I got a problem when trying to setup Easy Table of Contents work with Elementor page builder:
I added table of content to a post template by using [toc] shortcode in Elementor Shortcode widget. Table of Contents displays very nice. But It only work if I also turn on "Auto Insert" in Easy Table of Contents setting or turn on Insert (in post's Easy Table of Contents setting) for each post I want to show Table of Content. Otherwise, the post does not respond when I click any item in Table of Contents. But I just want to using Table of Content in the widget but not the post content. Did I do some thing wrong or we can fix it.

**Comment by shazahm1** [comment]
@Linhin 

I believe in Elementor you should use the TOC widget that comes with ezTOC, do not use the shortcode in a Elementor widget.

**Comment by Linhin** [comment]
Hi shazahm1, thank you for support. I use TOC widget that comes with ezTOC but it work the same way. Without inserting a TOC inside the post, TOC widget link won't work.

**Comment by shazahm1** [comment]
Related support forum thread:

- https://wordpress.org/support/topic/problem-using-elementor/

**Comment by Sanjeevsetu** [comment]
Hi @Linhin 

Its been long time. Since than so many version of plugin has been released and I hope new one would work as per your expectation. If You still face any issues please create new ticket as I am closing it.
