### ISSUE TITLE
Need to add a new feautre header label clickable like hamburger menu

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#487]
Ref ticket:- https://magazine3.in/conversation/141692?folder_id=21

Description:-
When we click on the header label, ETOC is open.

Issue screenshot
https://prnt.sc/UjX5Ziub3l3Y

**Comment by sajandara** [comment]
A user needs  similar functionality
Ref ticket:  https://magazine3.in/conversation/144758?folder_id=27
