### ISSUE TITLE
When TOC is not there do not load css

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/Easy-Table-of-Contents#491]
check in our pro extension as well.

**Comment by Sasirekhamarella** [comment]
https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/491

**Comment by oppenheimer-** [comment]
I opened the support ticket and I'd like to add: It's not only the CSS, but also the starting and ending <span>'s that get added. It seems that the visibility queries get mangled somewhere down the road. Thanks for looking into this, guys!

**Comment by Sanjeevsetu** [comment]
Hi @oppenheimer- 

We have fixed this issue in v 2.0.51. Please update the plugin and let us know.
