### ISSUE TITLE
Conflicting with Divi BodyCommerce plugin

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#493]
When we are using Divi Body Commerce with TOC, it generate Fatal error.

Fatal error : Allowed Memory size of 268435456 bytes exhausted ( tried to allocate 9682880 bytes ).

Reference Ticket -: https://magazine3.in/conversation/141236?folder_id=23

**Comment by muslimakhan** [comment]
Issue resolved on resolved on user end
