### ISSUE TITLE
Make compatibility with Generatepress gp-premium plugin

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#494]
When we add the TOC to posts or pages through generetapress elements, the TOC is not showing.

Ref Video: https://monosnap.com/direct/HSYendcQCZ37tMF5nU6qNBc9mhrvdU

Ref Ticket: https://magazine3.in/conversation/143952?folder_id=29

**Comment by muslimakhan** [comment]
Pro Added Code:
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/9ed5dd1b28775423331776daecdf5f483b9785b8
