### ISSUE TITLE
Need to add a feature to modify anchors

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#498]
There is a need to add a option using which we can make our anchor links shorter in length.

Reference ticket -: https://magazine3.in/conversation/145757?folder_id=23

**Comment by Sanjeevsetu** [comment]
This feature has been added in ticket https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/528 and pushed in v2.0.59.

Option name "Default Anchor Prefix For All" inside advanced tab
