### ISSUE TITLE
TOC Shortcode conflict with Grow Social Pro by Mediavine plugin

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#499]
When we add the TOC shortcode on the post or pages, the social icons that are added by Grow Social Pro by the Mediavine plugin are not showing.

Ref video: https://monosnap.com/direct/pR6BVs78aGE8irNxcXdZdWSGNDzb5g 

Ref Ticket: https://magazine3.in/conversation/145263?folder_id=29

**Comment by muslimakhan** [comment]
Issue resolved on user end
