### ISSUE TITLE
The subheadings open up and close once they come to sight and disappear.

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#5]
For extra-long content it would be great to have an option like this one http://codecanyon.net/item/jquerywikinav/full_screen_preview/7974274 (see behaviour of sidebar when scrolling), so that the subheadings open up and close once they come to sight and disappear.

ref:
http://connections-pro.com/2015/09/15/new-easy-table-of-contents-plugin-released/#comment-76323

**Comment by Sanjeevsetu** [comment]
We have added collapse subheadings in pro version. For more info, You can check out here https://tocwp.com/.

Please try it out and know us more changes. I am closing the ticket as ref url https://codecanyon.net/item/jquerywikinav/7974274 item is no longer available.
