### ISSUE TITLE
Remove the transient caching mechanism from the ez_toc_wp_check_browser_version() function.

### ISSUE THREAD

**Issue by nczz** [ahmedkaludi/Easy-Table-of-Contents#503]
Hi,

First of all, thank you for your hard work in maintaining such a great WordPress plugin! However, today I found that the `options` table in the database has increased a lot with `_site_transient_browser` data.

After debugging, I found that the `ez_toc_wp_check_browser_version()` method in the plugin caused this issue.

The transient handling in this method encrypts the `User Agent` using the `md5` method and saves it back to the database.

People with malicious intentions can use this method to cause the website's database to become bloated instantly by inserting different `User Agent` each time, which will also affect the website's performance.

I hope this method can be fixed so that I can reactivate this plugin again.

**Comment by Sanjeevsetu** [comment]
Hi @nczz 

Thank you so much for the appreciation. We have checked the issue and yes you are right. We will optimize the code and will fix it in next update.

**Comment by Sanjeevsetu** [comment]
Hi @nczz 

We have fixed the issue in our latest version 2.0.51. Please update to it and let us know
