### ISSUE TITLE
Error occurring after the latest update "Form elements do not have associated labels"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#505]
Bug: Error occurring after the latest updater "Form elements do not have associated labels" while testing the post in PageSpeed Insights https://pagespeed.web.dev tool

version: 2.0.50 

Ref screenshot: https://monosnap.com/direct/fRd7Qj8vZXfzOXzNoCQq4jfpYCneR1

Ref ticket: https://magazine3.in/conversation/150675?folder_id=27

**Comment by Sasirekhamarella** [comment]
same issue: https://wordpress.org/support/topic/add-ability-to-apply-aria-tag/

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/google-lighthouse-form-elements-do-not-have-associated-labels/
