### ISSUE TITLE
Headings miss their anchor If a title contains an apostrophe

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#529]
Headings miss their anchor If a title contains an apostrophe and lands a bit under its position while using the DIVI theme

Plugin version: 2.0.51.1
Ref ticket: https://magazine3.in/conversation/161023?folder_id=27
Ref video: https://monosnap.com/direct/VQRzJxjwrnQ5CDSYIDVi1YRr070l95

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/links-with-apostrophe-in-the-title-miss-the-anchor/

**Comment by akshaywali** [comment]
Code pushed in 2.0.54
