### ISSUE TITLE
Missing TOC Items

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#53]
@link https://github.com/shazahm1/Easy-Table-of-Contents/issues/13#issuecomment-409236182

Example: ![image](https://user-images.githubusercontent.com/918446/43464673-f9bfe150-94db-11e8-8b47-4cfbc118b927.png)

My settings are in Russian, sorry:
General: ![image](https://user-images.githubusercontent.com/918446/43464725-1958b6ea-94dc-11e8-82e4-bc28a409455a.png)
Advanced: ![image](https://user-images.githubusercontent.com/918446/43464789-3434ebf0-94dc-11e8-8cec-0e644866bd5b.png)

**Comment by shazahm1** [comment]
tagging @okainov

**Comment by shazahm1** [comment]
@okainov

Can you also share a screenshot of the TOC settings on for this page:

https://olegu.ru/reports/2016/norway/norvegiya-v-ijule-solo-na-avto-s-palatkoj/

**Comment by okainov** [comment]
It was a bit challenging to find where is it, I've never used those Settings on post page.
Interesting thing here is that all checkboxes were uncheched when I opened the page (I have all headers checked in global settings!), so I checked all the headings and also tried first one "insert toc", but it makes no change.
Post settings:
![image](https://user-images.githubusercontent.com/918446/43506404-3ab0fb8e-956a-11e8-87a6-70945b1bf996.png)

**Comment by Sanjeevsetu** [comment]
Ever since, Plugin has been released multiple times and has solved multiple issues. Please try our latest version and if issue still persist, Please create new ticket.
