### ISSUE TITLE
The visitor has to click twice on the toggle to open the Table Of Contents

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#530]
The visitor has to click twice on the toggle to open the Table Of Contents

Ref ticket: https://magazine3.in/conversation/159559?folder_id=27

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in ticket https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/378.
