### ISSUE TITLE
When the Pure CSS option is enabled, then the TOC heading and Toogle are not shown in the line.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#533]
When we set the TOC Loading Method On the pure CSS, then heading and Toogle are not shown in the single line.

Ref Screenshoot: https://prnt.sc/oAAN3Diy5lCY 

Ref Ticket: https://magazine3.in/conversation/162511?folder_id=29

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/toc-button-issue/
