### ISSUE TITLE
Add compatibility with the Acabado theme

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#547]
Add compatibility with the Acabado theme as the toggle is not working properly.

Ref ticket: https://magazine3.in/conversation/164691?folder_id=27

**Comment by Sanjeevsetu** [comment]
This issue is not valid. The theme has an option to deregister default jquery which was off. User needs to enable it if he/she wants to load toc based on js loading method.
