### ISSUE TITLE
Tap targets are not sized appropriately, an issue shown in the page speed insight tool.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#549]
Tap targets are not sized appropriately, an issue shown in the page speed insight tool while using the TOC

Ref Ticket: https://magazine3.in/conversation/168890?folder_id=29 

Ref screenshhot: https://prnt.sc/hojTeG2uB-id

**Comment by 77naveenop** [comment]
This is not a bug, some kind of configuration problem in setting
