### ISSUE TITLE
ToC number is showing in the middle of an item.

### ISSUE THREAD

**Issue by crm911** [ahmedkaludi/Easy-Table-of-Contents#551]
I don't know if the issue is with the Easy ToC plugin, or a bug in the Tooltip Tooltip Glossary plugin, which has triggered in the middle of  a ToC item. See 21.2 on [this page](https://www.autismspectrum.shop/2023/08/20-popular-sensory-toys-for-autistic-children/)

**Comment by Sanjeevsetu** [comment]
Hi @crm911 

I checked the given page and found that its a Tooltip Glossary plugin which has taken control of that particular anchor tag even that has changed jump link.

**Comment by Sanjeevsetu** [comment]
Hi @crm911 

Could you please contact us via https://tocwp.com/contact/ as the issue is only at your end and need some more info
