### ISSUE TITLE
Need to add an option for Sticky on mobile only

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#565]
When enabling Sticky TOC, it does show on desktop/mobile/tablet. There is a need to add an option to show it only on mobile.

Reference user -: https://wordpress.org/support/topic/hide-sticky-for-desktop-and-counter-for-sticky/

**Comment by sajandara** [comment]
Another user is requesting the same functionality: 
https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/565

**Comment by askcode21** [comment]
Another user : https://wordpress.org/support/topic/option-to-select-sticky-toc-for-mobile-or-desktop/#post-17105006

**Comment by amirhoseinsadeghi** [comment]
Another user is requesting the same functionality:
https://wordpress.org/support/topic/option-to-select-sticky-toc-for-mobile-or-desktop/

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/362
