### ISSUE TITLE
Heading links does not work if added using a shortcode in a template of usSolution core plugin by impreza theme

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#567]
Heading links does not work if added using a shortcode in a temple

Ref ticket: https://magazine3.in/conversation/169236?folder_id=27

Ref video: https://monosnap.com/direct/PmAI0Jo7CcXeluzJAXcl1pKGsVSntR

**Comment by sajandara** [comment]
The page template is created using the plugin **UpSolution Core** and the shortcode is added using a text block, when the template is used for post/pages the TOC links does not work.

The links start to work if the option Auto insert is enabled

**Comment by akshaywali** [comment]
Code pushed in 2.0.54
