### ISSUE TITLE
Add a new feature to customize the Background color of the Header Label

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#569]
Add a new feature to customize the TOC such as border, color navigation, and header background color.

Ref ticket: https://magazine3.in/conversation/173894?folder_id=27

Ref screenshot: https://monosnap.com/direct/HiMzd9wGG2PylEGs9ELGsHpoP13b55

**Comment by akshaywali** [comment]
pushed in 2.0.56 update
