### ISSUE TITLE
Need to make a compatibility with TravelTour theme builder.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#574]
Ref ticket:- https://magazine3.in/conversation/168435?folder_id=21

Description:-
The user added the ETOC shortcode with the help of the TravelTour theme builder, but ETOC is not visible on the front end.

Issue screenshot:-
https://prnt.sc/B280zYX6E4vG
https://prnt.sc/9BAx7mQ9AWi6

**Comment by akshaywali** [comment]
pushed in 2.0.55
