### ISSUE TITLE
We need to create an option where we can set a position for sticky TOC toggle.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#576]
1. We need to create an option where users can set the position of the sticky TOC toggle as top, middle, or bottom, and the TOC should open from above only.

**Another requirement is below.**

2. When we click on the links in the sticky TOC toggle, the TOC should get closed automatically on the desktop, as we have this option for the mobile version.

Ref Ticket: https://magazine3.in/conversation/184037?folder_id=29

**Comment by akshaywali** [comment]
pushed in 2.0.55
