### ISSUE TITLE
TOC in Generate Blocks widget disables main site navigation

### ISSUE THREAD

**Issue by thejparXCD** [ahmedkaludi/Easy-Table-of-Contents#578]
When using the TOC in a sticky rt sidebar widget, it disables all navigational and button links - using Generate Press/Generate Blocks Pro, Easy TOC Pro.

**Comment by akshaywali** [comment]
@thejparXCD  Did you get this issue recently after the update or it started happening earlier ?

**Comment by akshaywali** [comment]
@thejparXCD  We have just released the new version 2.0.54.1 , please update to that and see if the issue is fixed.
Please do confirm if the issue is fixed.

**Comment by Sanjeevsetu** [comment]
Hi @thejparXCD 

We are closing this ticket as it has been solved in last few updates. If you still face issue plz create new tickets
