### ISSUE TITLE
Bug after recent update

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#579]
Błąd typu E_PARSE został spowodowany w linii 1542 pliku /home///blog/wp-content/plugins/easy-table-of-contents/easy-table-of-contents.php. Komunikat błędu: syntax error, unexpected ” (T_ENCAPSED_AND_WHITESPACE), expecting ‘-‘ or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)

**Comment by akshaywali** [comment]
pushed in update 2.0.54.1
