### ISSUE TITLE
Sticky toggle  TOC is shown on the pages, but TOC is enabled on the post.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#582]
The sticky toggle TOC is showing on the pages, but enable support" and "auto insert" the TOC on posts only. but the sticky toggle TOC is still showing on the pages.

https://magazine3.in/conversation/185396?folder_id=29

**Comment by Sdaud1950** [comment]
Same issue with this user.

https://magazine3.in/conversation/187476?folder_id=29

**Comment by wegerl** [comment]
The same problem occurs in version 2.0.55. During testing in the developer environment, there were no problems at first. However, after activation via the editor and resetting the table of contents, the sticky toggle remains.

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/189222?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/190322?folder_id=21

**Comment by akshaywali** [comment]
Added Sticky  show on post type option

**Comment by Sanjeevsetu** [comment]
Another forum user : https://wordpress.org/support/topic/sticky-toc-showing-on-homepage-other-unwanted-pages/

**Comment by askcode21** [comment]
Another user: https://wordpress.org/support/topic/sticky-toggle-on-all-pages-whose-content-includes-subtitles/

**Comment by akshaywali** [comment]
pushed in update 2.0.56
