### ISSUE TITLE
Compatibility and Import/export tab do not show active color when they are clicked.

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/Easy-Table-of-Contents#585]
[Screencast 2023-09-05 17-07-09.webm](https://github.com/ahmedkaludi/Easy-Table-of-Contents/assets/11539242/f7e31b53-15b7-48d1-a2ab-994c6efed444)

**Comment by akshaywali** [comment]
pushed in 2.0.56 update
