### ISSUE TITLE
Add an option to load js in footer or header

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#586]
When TOC plugin is enabled with the Flatsome Child Theme, TOC is not showing.

Ref Ticket: https://magazine3.in/conversation/176197?folder_id=4

**Comment by Sanjeevsetu** [comment]
Actually by default all frontend js are loaded in footer but some themes or websites do not have footer hook defined in template and it stopes all functionality which are depend on js.

So, An option would be great here.
