### ISSUE TITLE
Need to create an option which Preserve Line Breaks in TOC.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#591]
User requested an option which preserves line breaks in TOC.

User original page: https://imgbb.com/ggC2TRw

modification user wants: https://imgbb.com/hsFzyF3

Here is the Reference ticket: https://wordpress.org/support/topic/preserve-line-breaks-2/

**Comment by nashitbarq** [comment]
Thank you so much for adding this feature. It is working flawlessly now.
