### ISSUE TITLE
Warning appears with compatibility function

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#595]
Ref ticket:-https://magazine3.in/conversation/190656?folder_id=21

Description:-
When the user activates the plugin, a warning appears, and it's an issue with the compatibility code.

Here is the screenshots
https://prnt.sc/MOnU071cejTL
https://prnt.sc/XUhfow1fRkwv
https://prnt.sc/0RkdMRaB3BXm ( code which create a issue)

**Comment by Rkroy** [comment]
https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/606

**Comment by Sanjeevsetu** [comment]
This ticket is duplicate of ticket no. https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/606. so I am closing it
