### ISSUE TITLE
Conflict issue with PrettyCreative theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#602]
Ref ticket:- https://magazine3.in/conversation/198006?folder_id=21

Description:-
Automatic toggle added in mobile version

Issue Screenshot:-
https://monosnap.com/direct/JdSDfo4J1mE6oOYIdPDxYoLN8evwWK (Mobile)
https://prnt.sc/W_yQiZqkKEAz (desktop)

**Comment by Sanjeevsetu** [comment]
It has been solved in our last update 2.0.56 and pushed
