### ISSUE TITLE
Conflict issue with Molongui Authorship plugin in 2.0.56 version

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#608]
The character encoding is getting changed in the German language and the issue has occurred after the last update.

Ref ticket: https://magazine3.in/conversation/199859?folder_id=27

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/200777?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/200777?folder_id=21

**Comment by askcode21** [comment]
Another user : https://wordpress.org/support/topic/special-character-heading-not-working/
