### ISSUE TITLE
Widget Auto-Highlight Issue After Update 2.0.56.1

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#610]
User Reports TOC Issue After Update 2.0.56.1: Active Links Missing During Scroll

Reference ticket: https://wordpress.org/support/topic/widget-does-not-auto-highlight/

**Comment by Sanjeevsetu** [comment]
Still have isssue for table of content widget. I am re opening the ticket

**Comment by MohammedAkramU7** [comment]
Another user facing issue:- https://magazine3.in/conversation/203770?folder_id=21
