### ISSUE TITLE
Incomplete CSS Classes in Version 2.0.57 Causing Style Issues

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#614]
User reported that In Version 2.0.57, incomplete CSS classes are affecting styling; ex, 'ez-toc-page-1' becomes '-page-1' and 'ez-toc-heading-level-2' becomes '-heading-level-2,' leading to disrupted styles.

Reference ticket: https://wordpress.org/support/topic/bug-since-version-2-0-51/

**Comment by Sanjeevsetu** [comment]
Released in v 2.0.57.1
