### ISSUE TITLE
Sticky TOC is showing on Blog pages

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#617]
When we enable sticky TOC, it shows on the blog page even if not enabled for the pages.

Reference : https://wordpress.org/support/topic/option-to-select-sticky-toc-for-mobile-or-desktop/  and https://magazine3.in/conversation/206261?folder_id=4

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/sticky-toggle-on-all-pages-whose-content-includes-subtitles/

**Comment by MohammedAkramU7** [comment]
Another user facing same issue: https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/617
