### ISSUE TITLE
Missing colons in TOC

### ISSUE THREAD

**Issue by sowiakps** [ahmedkaludi/Easy-Table-of-Contents#618]
Plugin removing colons from TOC.

Example: https://calamari.pl/blog/jak-przeprowadzic-w-pelni-zdigitalizowany-onboarding

Installed most recent version.

**Comment by Sanjeevsetu** [comment]
Hi @sowiakps 

Yeah, I can see colons have been removed while creating TOC but the issue is only happening at your end. Can you Please contact us via https://tocwp.com/contact

**Comment by Rkroy** [comment]
@sowiakps We've tried to look into this issue, but colon is loading properly at our end, hence it seems that the issue is occuring only on your site, so please contact us through this link https://tocwp.com/contact, so we can help you further.
