### ISSUE TITLE
Jump marks in TOC don't work correctly

### ISSUE THREAD

**Issue by jpboehm** [ahmedkaludi/Easy-Table-of-Contents#629]
The jump labels that the TOC outputs always take you to the top of the page and not to the headline in question.

The plugin has already been uninstalled and of course reset. The surprising thing is that after the page has been scrolled to the end, the TOC works every now and then. There is no regularity to be found.

How can we proceed there?

Best regards

**Comment by Sanjeevsetu** [comment]
Hi @jpboehm 

Could you share your issue's url here ? Just share so that we will see what's happening.

**Comment by Sanjeevsetu** [comment]
Hi @jpboehm 

You can contact us here https://tocwp.com/contact/  for better support. I am closing this ticket.
