### ISSUE TITLE
TOC plugin is not working with AJAX

### ISSUE THREAD

**Issue by roshni-bhatt15** [ahmedkaludi/Easy-Table-of-Contents#634]
We have displayed multiple blogs on a single blog page. When the user scrolls more, we display more blogs with the help of custom AJAX. TOC is not working on multiple blogs that are coming with AJAX.

Issue - https://prnt.sc/jsLMOzSDCuZ5

Please help us.

**Comment by 77naveenop** [comment]
Reference ticket -: https://magazine3.in/conversation/210557?folder_id=23
