### ISSUE TITLE
When we set the counter as a disc while using the viewMore option, then TOC CSS is not working fine.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#638]
When we set the counter as a disc while using the Viewmore option, the TOC CSS is not working fine.

Ref Ticket:https://magazine3.in/conversation/213929?folder_id=4

**Comment by Sanjeevsetu** [comment]
Incorrect use of <label for=FORM_ELEMENT> 

Affected resource : <label for="ez-toc-more-toggle-css" class="ez-toc-more-toggle-label"><span id="ez-toc-more-links-enabler" class="ez-toc-more-links-tgl">
