### ISSUE TITLE
Fix CSS Style Placement for Easy-Table-of-Contents WordPress Plugin

### ISSUE THREAD

**Issue by sinanouri** [ahmedkaludi/Easy-Table-of-Contents#639]
The Easy-Table-of-Contents WordPress plugin currently places the CSS style for 'ul.ez-toc-list a.ez-toc-link' after the closing </body> tag, causing HTML validation errors when checked with https://validator.w3.org/.

![image](https://github.com/ahmedkaludi/Easy-Table-of-Contents/assets/10999956/6fae1d66-c1d1-49dc-88b9-c517ecb22dc4)

**Comment by Sanjeevsetu** [comment]
Hi @sinanouri 

You are right. We checked the issue and it is valid one. We will fix it in our very next update.
