### ISSUE TITLE
A sticky toggle appears on the Author pages and it contains the headings of the latest post published by them.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#640]
A sticky toggle appears on the Author pages and it contains the headings of the latest post published by them.

Ref screenshot: https://monosnap.com/direct/CXewgarNqWlInqxmZlvxkkqbRLsL3N

Ref ticket: https://magazine3.in/conversation/214061?folder_id=27

**Comment by Sdaud1950** [comment]
We have disabled the option to show the sticky on the pages, but it still shows on the tag pages.
https://magazine3.in/conversation/217272?folder_id=29

**Comment by MFYDev** [comment]
Not just the author's page but also the specific tag page will also has this

**Comment by MFYDev** [comment]
Hello there, just updated to the latest version which is 2.0.59.

Fortunately it is not display on the tag page anymore, but it is still showing on my author page which is really weird.

**Comment by jvandriel** [comment]
Same here. I updated the plugin bit the sticky toggle still shown on the author profile page.

**Comment by jvandriel** [comment]
Today I noticed the sticky TOC is also showing on WP search result pages.

**Comment by jvandriel** [comment]
Thanks, the update seems to have resolved the issue.
