### ISSUE TITLE
Table of Contents show error - Undefined variable

### ISSUE THREAD

**Issue by nihargajjar** [ahmedkaludi/Easy-Table-of-Contents#641]
Notice: Undefined variable: label_below_html in /var/sites/blog/wp-content/plugins/easy-table-of-contents/includes/class.post.php on line 1458 

Error show in my website 

![image](https://github.com/ahmedkaludi/Easy-Table-of-Contents/assets/24638851/d2fbcb47-6117-4a9a-9b83-743452eabafa)

**Comment by pricejbp** [comment]
I have this issue as well. 

Warning: Undefined variable $label_below_html in /homepages/13/d4297724757/htdocs/wordpress/wp-content/plugins/easy-table-of-contents/includes/class.post.php on line 1458

**Comment by Sanjeevsetu** [comment]
Hi @nihargajjar & @pricejbp 

Thanks for reporting the bug. This is valid and has been fixed in the ticket https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/636. Please wait for the next update or you can get the code changed in it.
