### ISSUE TITLE
Disabling the automatic insertion of the table of contents is not working when we add the URL to the limit path option.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#643]
Disabling the automatic insertion of the table of contents is not working when we add the URL to the limit path option.

Ref video : https://monosnap.com/direct/pKikaZKelq1RAbyHhhY47MiteR5Xsg

Ref ticket:https://magazine3.in/conversation/213929?folder_id=29

**Comment by Sanjeevsetu** [comment]
This was suppose to be build that way. Not a valid one
