### ISSUE TITLE
Conflict issue with the Smooth Scroll Offset option

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#646]
Ref ticket:- https://magazine3.in/conversation/215747?folder_id=21

Description:-
When we set the Smooth Scroll Offset above, the 30 title links are not working properly while logging in.

Screenshot:-
https://monosnap.com/file/o14UGB3OPR6MiymGPwN9b4GDUavuBO

**Comment by Sdaud1950** [comment]
Same issue with this user:
https://magazine3.in/conversation/218131?folder_id=29

**Comment by sajandara** [comment]
A user is facing the same issue:
https://magazine3.in/conversation/218152?folder_id=27
