### ISSUE TITLE
A warning is appearing after the recent update

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#686]
A warning is appearing after the recent update

Warning: Undefined array key "sidebar_title_size" in /home/xs548308/uchii-code.com/public_html/wp-content/plugins/easy-table-of-contents/includes/class.widget-toc.php on line 233

Ref ticket: https://magazine3.in/conversation/233669?folder_id=27

**Comment by akshaywali** [comment]
pushed in 2.0.63
