### ISSUE TITLE
Warning appears in product widget sidebar

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#705]
Ref ticket: https://magazine3.in/conversation/247693?folder_id=21

Description:-
The user added the ETOC to the product sidebar widget, but a warning appears.

Warning: Undefined array key "sidebar_title_size" in /var/www/vhosts/***************wp-content/plugins/easy-table-of-contents/includes/class.widget-toc.php on line 233

Warning: Undefined array key "sidebar_title_size_unit" in /var/www/vhosts/*************/wp-content/plugins/easy-table-of-contents/includes/class.widget-toc.php on line 233

Issue screenshot:
https://prnt.sc/COtOmce5XO5n

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/Easy-Table-of-Contents/commit/df2a9f8c7e5a50fb06de6f381acaf94a0a1536df
