### ISSUE TITLE
"Exclude By Matching Url/String" ignores all but last entry

### ISSUE THREAD

**Issue by arencambre** [ahmedkaludi/Easy-Table-of-Contents#707]
No matter what I put in the **Exclude By Matching Url/String** field, everything is ignored except the very last line.

As an example, I currently have this as the field's value:
```
hello
test
path-forward
bsas-problems
```

The third should cause the TOC not to appear on https://scoutingmaverick.com/path-forward/, but it does. The fourth works: https://scoutingmaverick.com/bsas-problems/

**Comment by Sanjeevsetu** [comment]
Hi @arencambre 

Sorry for late reply. We have fixed some issues related to it. Give it one more try and remove any extra spaces before and after the strings.

**Comment by arencambre** [comment]
Thank you. Testing both above URLs, I am now good. I also changed the field's value to just be this, and it's still good:
```
path-forward
bsas-problems

```

**Comment by Sanjeevsetu** [comment]
@arencambre 

I am glad to hear the news. I am closing this ticket, If you need any further assistance you can create new ticket or contact us through https://tocwp.com/contact/.
