### ISSUE TITLE
( ! ) Deprecated: Function wp_specialchars is deprecated since version 2.8.0!

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/Easy-Table-of-Contents#709]
After adding [ez-toc-widget-sticky] in sidebar

( ! ) Deprecated: Function wp_specialchars is deprecated since version 2.8.0! Use esc_html() instead. in D:\WAMP\www\magazine3\wp-includes\functions.php

**Comment by akshaywali** [comment]
pushed in 2.0.63
