### ISSUE TITLE
Activating Schema breaks page layout

### ISSUE THREAD

**Issue by MackKaufmann** [ahmedkaludi/Easy-Table-of-Contents#713]
As soon as the SiteNavigation Schema function is activated, the layout of pages is broken. Even though pages are not included in the TOC. Posts work fine. 

Tested with and without JS (no error in console), tested with the default settings only activating Schema.

**Comment by Sanjeevsetu** [comment]
Hi @MackKaufmann 

It is throwing any critical error or just broke you design? We need more details on it or you can contact us via https://tocwp.com/contact/

**Comment by MackKaufmann** [comment]
No critical errors and also nothing in console. 

The design breaks, images are missing and some buttons on pages are not working anymore

**Comment by Sanjeevsetu** [comment]
Hi @MackKaufmann 

Have you enabled the option "SiteNavigation Schema"?. If yes than once disabled it and check if issue is fixed or not?
