### ISSUE TITLE
Conflict issue with GP Premium Element Support option(user specific issue)

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#724]
Ref ticket: https://magazine3.in/conversation/256078?folder_id=21

Description:
When we enabled the GP Premium Element Support option, the site crashed, and the view more option was not working on the user end.

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/259f4dfb04e4149b639e871d7ef359868c9ba5f9

**Comment by Sanjeevsetu** [comment]
It has been
