### ISSUE TITLE
Warning: Undefined array key "s_blockqoute_checkbox"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#728]
Warning: Undefined array key "s_blockqoute_checkbox"

Ref ticket: https://magazine3.in/conversation/259789?folder_id=27

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/error-log-129/

**Comment by Sdaud1950** [comment]
same issue with this user : https://magazine3.in/conversation/261609?folder_id=29

**Comment by sajandara** [comment]
Another user is facing the same issue:
https://magazine3.in/conversation/261714?folder_id=27

**Comment by askcode21** [comment]
https://wordpress.org/support/topic/warning-undefined-array-key-s_blockqoute_checkbox/  another user
