### ISSUE TITLE
Need to exclude heading from query loop feature

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#730]
Ref ticket: https://magazine3.in/conversation/257894?folder_id=21

Description:-
The user added the title with the help of the query loop feature but wanted to exclude it from ETOC with the help of the class, but we couldn't add the class manually.

Here is the screenshot for the query lopp feature.
https://prnt.sc/JMepAn7XLVKv
https://prnt.sc/I1ltKcWLOTyf

**Comment by kumawatvikas** [comment]
Ref : - https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/7f7f8976eed32bb0dcfe1c5e75884c620648d6e8
