### ISSUE TITLE
Need an option or shortcode like [initial_view="Show"] for specific pages/post.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#732]
One user has reached out to us regarding a concern. Our "Initial View" option and shortcode [initial_view="hide"] work well on all pages/posts to hide the Table of Contents (TOC). However, User require an alternative to prevent application on all pages.   Like whether we can choose which pages display the TOC and which do not. Therefore, we need a shortcode like [initial_view="show"]

Reference ticket: https://wordpress.org/support/topic/shortcode-to-initially-show-table/

**Comment by akshaywali** [comment]
pushed in Easy TOC 2.0.66
