### ISSUE TITLE
visualizazione bug

### ISSUE THREAD

**Issue by playretroitalia** [ahmedkaludi/Easy-Table-of-Contents#734]
In sticky shortcode the visualizazion is not correct
see the pix
i try different browser

the 1 point is covered by title
![bugg](https://github.com/ahmedkaludi/Easy-Table-of-Contents/assets/166615820/31487dc0-98c2-46dc-b46b-2ad2658e5ff3)

**Comment by Sanjeevsetu** [comment]
Hi @playretroitalia 

title font size is big, just decrease it or expand sticky container width

**Comment by Sanjeevsetu** [comment]
Hi @playretroitalia 

Are you able to solve the issue ? If not than you can contact us through https://tocwp.com/contact/
