### ISSUE TITLE
Flexible Contents disappearing when using EZ TOC PRO with ACF PRO and multiple headings inside text editor blocks

### ISSUE THREAD

**Issue by eartahhj** [ahmedkaludi/Easy-Table-of-Contents#736]
Hi, this is a very particular case, I reckon, but I have this weird situation where the contents made with ACF Pro Flexible Content field are not being displayed in this case:

- ACF Pro is Enabled
- Flexible Content is being used on a Page (post_type=page)
- In these flexible contents, a text editor (wysiwig - tinymce) is being used
- In the same text editor block, multiple headings are inserted (h1-h6), being of the same heading level or different level - OR, in general, when there is more than one heading when using flexible contents with wyswig editors

When all these conditions are true, doing `var_dump(have_rows('field_with_flexible_content'))` returns false. As soon as you leave only one single heading in the text editor block, that var_dump will return true.

So this is very weird indeed, but I have tried disabling the TOC Pro plugin and the problem goes away.
I believe this could happen because of course TOC Pro adds support with ACF, and maybe it goes crazy if there are multiple headings inside the content of a field made with Flexible Contents.

Even funnier is the fact that the TOC is actually displayed correctly in the page, using a shortcode, but the Flexible Content made with ACF apparently disappears.

I am now unable to show a live site with this problem, but I believe you can reproduce the problem kinda easily if it exists. I will see if I am able to setup a test site where to try this out.

For now I add this here as a bug, if I am wrong feel free to close it or I will close it if I see it's due to something non related to TOC Pro.

**Comment by Sanjeevsetu** [comment]
Hi @eartahhj 

We will sure help you on this matter. Kindly contact us through https://tocwp.com/contact because the issue needs to be debugged.
