### ISSUE TITLE
Conflict issue with custom theme(user specific issue)

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#750]
Ref ticket: https://magazine3.in/conversation/273075?folder_id=21

Description:-
The user utilized a custom theme to incorporate post content using the ACF field, but encountered an issue where the headings were not properly aligned in the table of contents. Specifically, the second heading appears at the end

Issue screenshot:-
https://prnt.sc/4S6b5YLQI3Ng

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/806f8918779e665a666a7e786a3d31d96a4a7815

**Comment by akshaywali** [comment]
pushed in pro version 1.0.27
