### ISSUE TITLE
ETOC version 2.0.66 giving **Fatal error**: Uncaught TypeError: method_exists():

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#752]
Multiple user reported this issue that latest version 2.0.66 giving fatal error and breaking website. 

Reference ticket: https://wordpress.org/support/topic/the-last-update-broke-my-site-4/

**Comment by deLisle** [comment]
They have released a fixed that can be updated now.

**Comment by Sanjeevsetu** [comment]
Fixed in v2.0.66.1
