### ISSUE TITLE
Sticky TOC appears on homepage without enabling option when front page is set

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/Easy-Table-of-Contents#754]
One user reached out to us for this concern that sticky toc appears on homepage without enabling the option. 

Reference Ticket: https://wordpress.org/support/topic/sticky-toc-at-homepage/

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/disabling-sticky-toc-for-homepage/

**Comment by akshaywali** [comment]
pushed in version 2.0.67
