### ISSUE TITLE
Block editor background color issue in backend

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#756]
When using TOC, background color of block editor ( gutenberg ) changes when using table of content.

Reference user -: https://magazine3.in/conversation/273815?folder_id=23

**Comment by akshaywali** [comment]
Issue is due to new update of block editor, when there is Meta boxes on the post  background changes to white , if no meta boxes are  present then correct background color is displayed.
