### ISSUE TITLE
TOC conflict with Beaver Builder Plugin (Pro Version) pluigin 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#759]
TOC conflict with Beaver Builder Plugin (Pro Version) pluigin 

Ref Ticket : https://magazine3.in/conversation/277499?folder_id=29

**Comment by akshaywali** [comment]
Issue was due to some themes custom CSS , which has been fixed on the user  site . This doesn't required global update
