### ISSUE TITLE
User site is working slowly due to an issue with the preg_match_all function. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#762]
The user site is working slowly. In the x-ray report sent to the hosting team, they found the preg_match_all function to be a casung issue. 

preg_match_all
/home/.../public_html/wp-content/plugins/easy-table-of-conte
nts/includes/inc.cord-functions.php:245

Ref ticket : https://magazine3.in/conversation/274941?folder_id=29

**Comment by Sanjeevsetu** [comment]
The issues was user specific and has been solved at user end
