### ISSUE TITLE
Need create an option to set the Read Time in Minutes option for individual posts or pages and set the translation for reading time.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#763]
1.Need create an option to set the Read Time in Minutes option for individual posts

2.  Set the translation for reading time.

Ref ticket:https://magazine3.in/conversation/281182?folder_id=29

**Comment by akshaywali** [comment]
pushed in version 2.0.67 and pro 1.0.27
