### ISSUE TITLE
TOC heading is getting mismatched while using ACF PRO and the Waterfront theme. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/easy-table-of-contents#765]
Stickey TOC heading is getting mismatched while using ACF PRO and the Waterfront theme. 

Ref screenshoot https://prnt.sc/6vtcMdnzkKbh  https://prnt.sc/vIWDXWnvRBOV 

Ref ticket:https://magazine3.in/conversation/282033?folder_id=29

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/806f8918779e665a666a7e786a3d31d96a4a7815
