### ISSUE TITLE
Php warning 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#776]
\"wp-content/plugins/easy-table-of-contents-pro/compatibility.php on line 115; PHP message: PHP Warning: Trying to access array offset on null \"

ref ticket :https://magazine3.in/conversation/289395?folder_id=29

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/788
