### ISSUE TITLE
Sticky ETOC CSS automatically added in homepage

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/easy-table-of-contents#777]
Ref ticket: https://magazine3.in/conversation/285721?folder_id=21

Description:
When we enable the sticky ETOC on post but CSS reflected in home page's.

Here is the screenshot
https://prnt.sc/JcskGQfivHFq

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/787
