### ISSUE TITLE
 Latest Version 2.0.68.1 causing functionality of "Inline CSS" Option in ETOC.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/easy-table-of-contents#787]
One user reported that the Inline CSS option isn't working as expected when enabled in the new update, version 2.0.68.1.

Reference ticket: https://wordpress.org/support/topic/2-0-68-1-inline-css-show-as-hierarchy-checked-and-counter-type/

**Comment by Sdaud1950** [comment]
Same issue : https://magazine3.in/conversation/295851?folder_id=29

**Comment by MohammedAkramU7** [comment]
another user:- https://magazine3.in/conversation/298528?folder_id=21

**Comment by MohammedAkramU7** [comment]
https://magazine3.in/conversation/296458?folder_id=21

**Comment by askcode21** [comment]
https://wordpress.org/support/topic/numbers-in-list-2-0-68-1-missing/.  counter issue.
