### ISSUE TITLE
Php warning.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/easy-table-of-contents#788]
Ref ticket : https://magazine3.in/conversation/296264?folder_id=29

**Comment by Sanjeevsetu** [comment]
Commit Ref : https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/af15b2a67bca1847f392264761976889c0700452

**Comment by Sanjeevsetu** [comment]
Related : https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/776
