### ISSUE TITLE
Need to clean the autoloaded data "ez-toc-post-content-core-level from the database.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/easy-table-of-contents#793]
Need to clean the autoloaded data "ez-toc-post-content-core-level from the database.

https://magazine3.in/conversation/302067?folder_id=29

**Comment by askcode21** [comment]
same conern: https://wordpress.org/support/topic/is-autoload-needed-ez-toc-post-content-core-level/
