### ISSUE TITLE
Copy Shortcode buttons are not working

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/easy-table-of-contents#798]
Copy Shortcode buttons are not working

Ref ticket: https://magazine3.in/conversation/302584?folder_id=27

**Comment by tomcoady** [comment]
The issue can be found below this text in the settings page:
`You` can use the following shortcode to `Easy Table of Contents` display in your particular post or page. [Learn More](https://tocwp.com/docs/knowledge-base/how-to-add-toc-with-shortcode/)
 Copy shortcode
