### ISSUE TITLE
Smooth Scroll Offset value Only working on clicking the toc item twice.

### ISSUE THREAD

**Issue by sewa-tech** [ahmedkaludi/easy-table-of-contents#799]
I have already enabled the smooth scroll option and set the value of smooth scroll offset 140 pixel but it is only working when a double click the table of content link for reference. I am adding my website url below:

https://computerexpertadelaide.com.au/uncategory/why-is-your-computer-slow-top-causes-and-quick-fixes/

**Comment by Sanjeevsetu** [comment]
Hi @sewa-tech 

Thanks for contacting us.

I checked the given url and found that it was working on one click. Could you re check it with clearing cache if any.

**Comment by sewa-tech** [comment]
it's working on one click but as you can see i have a sticky header so the anchored content when clicked, is getting behind the header menu so to solve that i have given Scroll Offset value more than my header height but it's not using that  and it still getting behind the header.

**Comment by sewa-tech** [comment]
after enabling the jump link works without adding ids in the URL, my issue was solve :)
