### ISSUE TITLE
Preserve-Linebreaks is broken.

### ISSUE THREAD

**Issue by nashitbarq** [ahmedkaludi/easy-table-of-contents#806]
I use this feature on Urdu text, and it was working perfectly before. But since the latest update, it is broken. Here is how it looks like on version **2.0.69**:

![Screenshot 2024-09-02 172015](https://github.com/user-attachments/assets/fd2dcc2d-442f-4498-b2d3-9e019722c500)

The highlighted parts are supposed to be on the new line.

I tested the previous version by downgrading the plugin to **2.0.59** and it worked perfectly. Here, the highlighted parts are appearing on a new line, the way it is supposed to work:

![Screenshot 2024-09-02 174504](https://github.com/user-attachments/assets/b21f28e7-428e-4602-9bcc-cc0e22741eb1)

Link for demonstrated screenshot-page: https://aadhibaat.org/zarb-e-kaleem-71-maqsood/ (the site is using version 2.0.59 for now)

**Comment by Sanjeevsetu** [comment]
Hi @nashitbarq 

Thanks for reporting the bug. Could you please contact through https://tocwp.com/contact/ for better understanding of issue.

**Comment by nashitbarq** [comment]
Thank you for response, I have contacted through the provided link. Awaiting your kind response.

Also, I have noticed that version 2.0.69 is doing something strange; it joins the last letter of first line with the last first letter of second line

for example

![Screenshot 2024-09-03 195949](https://github.com/user-attachments/assets/98d2003a-936f-45a8-a1cc-ce598f9c00e4)

@Sanjeevsetu

**Comment by Sanjeevsetu** [comment]
Hi @nashitbarq 

We just committed the fix for this ticket. You can see above commit reference. It will be released in 2.0.70

**Comment by akshaywali** [comment]
Pushed in 2.0.70
