### ISSUE TITLE
ACF headings were not showing in the TOC.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/easy-table-of-contents#811]
ACF headings were not showing in the TOC.

Ref Ticket: https://magazine3.in/conversation/310208?folder_id=29

**Comment by akshaywali** [comment]
Ref commit  :  https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/e6dc0aa9af16b4df9b7c7bd15712646dd4d7614a

**Comment by akshaywali** [comment]
pushed in PRO 1.0.29
