### ISSUE TITLE
Issue with "TOC open on load" option in Sticky TOC feature.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/easy-table-of-contents#815]
Ref ticket: https://magazine3.in/conversation/311550?folder_id=21

Description:-
When we enable the "TOC Open on Load" option in Sticky TOC, it loads correctly on the front end after a refresh. However, the sticky icon also appears along with it.

Here is the screenshot
https://prnt.sc/7z11gLuhP1D3

**Comment by akshaywali** [comment]
pushed in 2.0.71
