### ISSUE TITLE
Incorrect Symbols Displaying When Adding %PAGE_NAME% as Header Label

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/easy-table-of-contents#816]
Incorrect Symbols Displaying in TOC Header Label When Using %PAGE_NAME% in Spanish lang.(Page content should be in Spanish )

Ref Screenshoot : https://prnt.sc/br39cr6Umwvm

Ref ticket : https://magazine3.in/conversation/312429?folder_id=29

**Comment by akshaywali** [comment]
pushed in 2.0.70
