### ISSUE TITLE
Exclude Blockqoute feature not working properly.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/easy-table-of-contents#825]
Ref ticket: https://magazine3.in/conversation/316618?folder_id=21

Description:
When we enable the 'Exclude Blockquote' option along with the position setting, the Blockquote content is not being excluded as expected.

**Comment by akshaywali** [comment]
Ref  : https://github.com/ahmedkaludi/easy-table-of-contents/commit/6d4a20b00d422db4ac64be2e9fc3e52db8b8240e

**Comment by akshaywali** [comment]
pushed in 2.0.70
