### ISSUE TITLE
The Sticky Toc title does not shift to the right in the option Heading Text Direction selected as Right to Left is selected

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/easy-table-of-contents#833]
1. The Sticky Toc title does not shift to the right in the option Heading Text Direction selected as Right to Left is selected
2. The TOC subheadings do not have space in front of them in the Heading Text Direction option Right to left
3. Need to add an option to add space in between headings in Sticky TOC

Ref ticket: https://magazine3.in/conversation/318405?folder_id=27

**Comment by akshaywali** [comment]
pushed in PRO 1.0.30
