### ISSUE TITLE
'Header Label' Option Not Updating in post individually

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/easy-table-of-contents#837]
Multiple users have reported this issue: when they try to change the 'Header Label' in the Classic Editor, it doesn’t update on the frontend and still shows 'Table of Contents.

Note: "Header Label" option from plugin settings works fine but not in classic editor.

Reference ticket: https://wordpress.org/support/topic/individual-header-title-not-shown/

**Comment by Sdaud1950** [comment]
same issue : https://magazine3.in/conversation/322421?folder_id=29

**Comment by akshaywali** [comment]
pushed in 2.0.71
