### ISSUE TITLE
PHP 8.3 Error: Undefined Array Key 'navigation_scroll_bar' in class-eztoc-widgetsticky.php

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/easy-table-of-contents#842]
One user reported this issue ,"PHP error:

Undefined array key “navigation_scroll_bar” in /home/cpaneluser/public_html/wp-content/plugins/easy-table-of-contents/includes/class-eztoc-widgetsticky.php on line 258"

Reference ticket: https://wordpress.org/support/topic/php-error-671/

**Comment by akshaywali** [comment]
pushed in 2.0.71
