### ISSUE TITLE
Need to make floating layout for Sticky ETOC

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/easy-table-of-contents#844]
Ref ticket: https://magazine3.in/conversation/312990?folder_id=21

Description
We need to create a new design for the Sticky ETOC that will float and allow the user to change its position to either the top or bottom, depending on their preference

Screenshot of both versions

Mobile
https://prnt.sc/jjC5g4qyEMh0
https://prnt.sc/lSFw4ts52AwL

Desktop
https://monosnap.com/direct/o7LGxCPTDXEehhBeJoOwzYqauFXIsh

**Comment by akshaywali** [comment]
Pushed in PRO 1.0.30
