### ISSUE TITLE
Prevent FOUC when "Initially hide the table of contents" option is enabled.

### ISSUE THREAD

**Issue by NEMONAUT** [ahmedkaludi/Easy-Table-of-Contents#91]
Not sure if this should be considered an enhancement or a bugfix...

Sometimes the contents of the TOC show up briefly during page load. Adding an inline "display: none;" style to the `<ul>` on below linked line when the "initially hide" option is enabled would fix this. I have tested this on both 1.7 and 2.0-rc5.

https://github.com/shazahm1/Easy-Table-of-Contents/blob/a1e9080f44bbae47edf0b32e9906a3a5af487d98/includes/class.post.php#L861

**Comment by shazahm1** [comment]
I understand why adding this is desirable, but, from a support perspective, I do not want to. One of the things I do most is provide support for WP plugins. The number one  thing I see on sites, even if they appear to be working, is fatal JavaScript errors. Guaranteed, if the display none is added, I will never stop receiving support requests about the TOC not showing. So, I always default to showing and then allow JS, if actually running, to hide the TOC.

**Comment by shazahm1** [comment]
I'll keep this open for now, but tagging as wontfix. Perhaps my mind will be changed in the future.

**Comment by Sanjeevsetu** [comment]
Hi @NEMONAUT 

I think. Similar kind of changes have been done in our latest version. Please try once our latest version and let us know ? If You have any other queries, you can create new ticket or contact our support.
