### ISSUE TITLE
Improve SEO Options

### ISSUE THREAD

**Issue by shazahm1** [ahmedkaludi/Easy-Table-of-Contents#93]
On by default, but add options for

- Add noindex on TOC links
- Wrap TOC nav in noindex tags.

**Comment by feastdesignco** [comment]
This is unnecessary - Google by default strips fragments and doesn't count them as independent pages: https://support.google.com/webmasters/answer/7451184?hl=en

**Comment by Sanjeevsetu** [comment]
@feastdesignco 

Yes, you are right, this is unnecessary. Google automatically does the thing for us. I am closing the ticket.
