### ISSUE TITLE
Fixed/Sticky Toc

### ISSUE THREAD

**Issue by tahamaddam** [ahmedkaludi/Easy-Table-of-Contents#96]
Great Plugin.

However, can we fix it inside the post/page? Just like [here](http://demo.webvars.com/fixedtoc/demo-3/)

As you can see that in the above example, it is part of the post/page and not sidebar therefore it displays even on mobile devices (with tap on toc icon)

**Comment by shazahm1** [comment]
Thanks for the suggestion. That site is using the [Fixed TOC plugin](https://codecanyon.net/item/fixed-toc-wordpress-plugin/7264676). I think this would be a great addition as a commercial addon.

**Comment by shazahm1** [comment]
ref:

- https://wordpress.org/support/topic/sticky-table-of-contents-toc-widget/

**Comment by Zabi09** [comment]
Added in Easy TOC PRO
